-- Generated custom types and matchups data
local T = {}

T.types = {
  DARK = { name = "DARK", category = "special" },
  FAIRY = { name = "FAIRY", category = "special" },
  STEEL = { name = "STEEL", category = "physical" },
}

T.matchups = {
  { attacker = "DARK", defender = "BUG", multiplier = 10 },
  { attacker = "DARK", defender = "NORMAL", multiplier = 10 },
  { attacker = "DARK", defender = "WATER", multiplier = 10 },
  { attacker = "DARK", defender = "DRAGON", multiplier = 10 },
  { attacker = "DARK", defender = "GROUND", multiplier = 10 },
  { attacker = "DARK", defender = "FIGHTING", multiplier = 5 },
  { attacker = "DARK", defender = "POISON", multiplier = 10 },
  { attacker = "DARK", defender = "FIRE", multiplier = 10 },
  { attacker = "DARK", defender = "FLYING", multiplier = 10 },
  { attacker = "DARK", defender = "GHOST", multiplier = 20 },
  { attacker = "DARK", defender = "ROCK", multiplier = 10 },
  { attacker = "DARK", defender = "ICE", multiplier = 10 },
  { attacker = "DARK", defender = "GRASS", multiplier = 10 },
  { attacker = "DARK", defender = "ELECTRIC", multiplier = 10 },
  { attacker = "DARK", defender = "PSYCHIC_TYPE", multiplier = 20 },
  { attacker = "DARK", defender = "DARK", multiplier = 5 },
  { attacker = "DARK", defender = "STEEL", multiplier = 5 },
  { attacker = "DARK", defender = "FAIRY", multiplier = 5 },
  { attacker = "STEEL", defender = "BUG", multiplier = 10 },
  { attacker = "STEEL", defender = "NORMAL", multiplier = 10 },
  { attacker = "STEEL", defender = "WATER", multiplier = 5 },
  { attacker = "STEEL", defender = "DRAGON", multiplier = 10 },
  { attacker = "STEEL", defender = "GROUND", multiplier = 10 },
  { attacker = "STEEL", defender = "FIGHTING", multiplier = 10 },
  { attacker = "STEEL", defender = "POISON", multiplier = 10 },
  { attacker = "STEEL", defender = "FIRE", multiplier = 5 },
  { attacker = "STEEL", defender = "FLYING", multiplier = 10 },
  { attacker = "STEEL", defender = "GHOST", multiplier = 10 },
  { attacker = "STEEL", defender = "ROCK", multiplier = 20 },
  { attacker = "STEEL", defender = "ICE", multiplier = 20 },
  { attacker = "STEEL", defender = "GRASS", multiplier = 10 },
  { attacker = "STEEL", defender = "ELECTRIC", multiplier = 5 },
  { attacker = "STEEL", defender = "PSYCHIC_TYPE", multiplier = 10 },
  { attacker = "STEEL", defender = "DARK", multiplier = 10 },
  { attacker = "STEEL", defender = "STEEL", multiplier = 5 },
  { attacker = "STEEL", defender = "FAIRY", multiplier = 20 },
  { attacker = "FAIRY", defender = "BUG", multiplier = 10 },
  { attacker = "FAIRY", defender = "NORMAL", multiplier = 10 },
  { attacker = "FAIRY", defender = "WATER", multiplier = 10 },
  { attacker = "FAIRY", defender = "DRAGON", multiplier = 20 },
  { attacker = "FAIRY", defender = "GROUND", multiplier = 10 },
  { attacker = "FAIRY", defender = "FIGHTING", multiplier = 20 },
  { attacker = "FAIRY", defender = "POISON", multiplier = 5 },
  { attacker = "FAIRY", defender = "FIRE", multiplier = 5 },
  { attacker = "FAIRY", defender = "FLYING", multiplier = 10 },
  { attacker = "FAIRY", defender = "GHOST", multiplier = 10 },
  { attacker = "FAIRY", defender = "ROCK", multiplier = 10 },
  { attacker = "FAIRY", defender = "ICE", multiplier = 10 },
  { attacker = "FAIRY", defender = "GRASS", multiplier = 10 },
  { attacker = "FAIRY", defender = "ELECTRIC", multiplier = 10 },
  { attacker = "FAIRY", defender = "PSYCHIC_TYPE", multiplier = 10 },
  { attacker = "FAIRY", defender = "DARK", multiplier = 20 },
  { attacker = "FAIRY", defender = "STEEL", multiplier = 5 },
  { attacker = "FAIRY", defender = "FAIRY", multiplier = 10 },
  { attacker = "BUG", defender = "DARK", multiplier = 20 },
  { attacker = "BUG", defender = "STEEL", multiplier = 5 },
  { attacker = "BUG", defender = "FAIRY", multiplier = 5 },
  { attacker = "NORMAL", defender = "DARK", multiplier = 10 },
  { attacker = "NORMAL", defender = "STEEL", multiplier = 5 },
  { attacker = "NORMAL", defender = "FAIRY", multiplier = 10 },
  { attacker = "WATER", defender = "DARK", multiplier = 10 },
  { attacker = "WATER", defender = "STEEL", multiplier = 10 },
  { attacker = "WATER", defender = "FAIRY", multiplier = 10 },
  { attacker = "DRAGON", defender = "DARK", multiplier = 10 },
  { attacker = "DRAGON", defender = "STEEL", multiplier = 5 },
  { attacker = "DRAGON", defender = "FAIRY", multiplier = 0 },
  { attacker = "GROUND", defender = "DARK", multiplier = 10 },
  { attacker = "GROUND", defender = "STEEL", multiplier = 20 },
  { attacker = "GROUND", defender = "FAIRY", multiplier = 10 },
  { attacker = "FIGHTING", defender = "DARK", multiplier = 20 },
  { attacker = "FIGHTING", defender = "STEEL", multiplier = 20 },
  { attacker = "FIGHTING", defender = "FAIRY", multiplier = 5 },
  { attacker = "POISON", defender = "DARK", multiplier = 10 },
  { attacker = "POISON", defender = "STEEL", multiplier = 0 },
  { attacker = "POISON", defender = "FAIRY", multiplier = 20 },
  { attacker = "FIRE", defender = "DARK", multiplier = 10 },
  { attacker = "FIRE", defender = "STEEL", multiplier = 20 },
  { attacker = "FIRE", defender = "FAIRY", multiplier = 10 },
  { attacker = "FLYING", defender = "DARK", multiplier = 10 },
  { attacker = "FLYING", defender = "STEEL", multiplier = 5 },
  { attacker = "FLYING", defender = "FAIRY", multiplier = 10 },
  { attacker = "GHOST", defender = "DARK", multiplier = 5 },
  { attacker = "GHOST", defender = "STEEL", multiplier = 5 },
  { attacker = "GHOST", defender = "FAIRY", multiplier = 10 },
  { attacker = "ROCK", defender = "DARK", multiplier = 10 },
  { attacker = "ROCK", defender = "STEEL", multiplier = 5 },
  { attacker = "ROCK", defender = "FAIRY", multiplier = 10 },
  { attacker = "ICE", defender = "DARK", multiplier = 10 },
  { attacker = "ICE", defender = "STEEL", multiplier = 5 },
  { attacker = "ICE", defender = "FAIRY", multiplier = 10 },
  { attacker = "GRASS", defender = "DARK", multiplier = 10 },
  { attacker = "GRASS", defender = "STEEL", multiplier = 5 },
  { attacker = "GRASS", defender = "FAIRY", multiplier = 10 },
  { attacker = "ELECTRIC", defender = "DARK", multiplier = 10 },
  { attacker = "ELECTRIC", defender = "STEEL", multiplier = 10 },
  { attacker = "ELECTRIC", defender = "FAIRY", multiplier = 10 },
  { attacker = "PSYCHIC_TYPE", defender = "DARK", multiplier = 0 },
  { attacker = "PSYCHIC_TYPE", defender = "STEEL", multiplier = 5 },
  { attacker = "PSYCHIC_TYPE", defender = "FAIRY", multiplier = 10 },
}

return T
