return {
  animations = true,
  battleBg = "white",
  battleFit = "fixed",
  battleLayout = "og",
  battleStyle = "shift",
  colors = "gbc",
  dateFormat = "device",
  faithfulRes = 0,
  fpsCap = 60,
  gbcfx = 0,
  haptics = "light",
  modIndexCache = {},
  modIndexes = {},
  modProfiles = {},
  modProfilesSeeded = false,
  modUpdateCache = {},
  mods = {},
  modsByVersion = {
    blue = {
      ["Kanto-Reforged"] = true,
    },
    gold = {
      ["Kanto-Reforged"] = true,
    },
    red = {
      ["Kanto-Reforged"] = true,
    },
    yellow = {
      ["Kanto-Reforged"] = true,
    },
  },
  modsByVersionMigrated = true,
  modsGen2 = {},
  musicFilter = 0,
  musicVol = 7,
  performance = "auto",
  pikaVol = 7,
  pipelines = {},
  ruleset = "gen1_faithful",
  sfxVol = 7,
  speedBattle = 1,
  speedMenu = 1,
  speedOverworld = 1,
  textSpeed = 3,
  tilt = 0,
  timeFormat = "device",
  touchControls = {
    enabled = true,
  },
  uiLayout = "centered",
  videoMode = "windowed",
  voidFill = "trees",
  zoom = 0,
}
