-- Short in-game blurbs for the party summary ability page.
-- Written like Gen 1 dex lines: terse, no modern jargon.

local AbilityText = {
  AIR_LOCK = "Negates the effects of weather.",
  BATTLE_ARMOR = "Protects from critical hits.",
  BLAZE = "Powers up FIRE moves in a pinch.",
  CHLOROPHYLL = "Boosts SPEED in sunshine.",
  CLEAR_BODY = "Prevents foes from lowering stats.",
  COLOR_CHANGE = "Changes type to match a hit.",
  COMPOUND_EYES = "Raises move accuracy.",
  CURSED_BODY = "May disable a move that hits it.",
  CUTE_CHARM = "Contact may infatuate the foe.",
  DAMP = "Prevents self-destruction moves.",
  DRIZZLE = "Summons rain when it enters.",
  DROUGHT = "Summons sun when it enters.",
  EARLY_BIRD = "Awakens quickly from sleep.",
  EFFECT_SPORE = "Contact may inflict a status.",
  FLAME_BODY = "Contact may burn the foe.",
  FLASH_FIRE = "Immune to FIRE moves. Powers up its own FIRE moves.",
  FORECAST = "Changes type with the weather.",
  GUTS = "Boosts ATTACK when statused.",
  HUSTLE = "Boosts ATTACK but cuts accuracy.",
  HYPER_CUTTER = "Prevents ATTACK from falling.",
  ILLUMINATE = "Raises the chance of meeting wild POKeMON.",
  IMMUNITY = "Prevents poisoning.",
  INNER_FOCUS = "Prevents flinching.",
  INSOMNIA = "Prevents sleep.",
  INTIMIDATE = "Lowers the foe's ATTACK.",
  KEEN_EYE = "Prevents accuracy from falling.",
  LEVITATE = "Immune to GROUND moves.",
  LIGHTNING_ROD = "Immune to ELECTRIC moves.",
  LIMBER = "Prevents paralysis.",
  LIQUID_OOZE = "Hurts foes that drain HP.",
  MAGMA_ARMOR = "Prevents freezing.",
  MAGNET_PULL = "Prevents STEEL foes from fleeing.",
  MARVEL_SCALE = "Boosts DEFENSE when statused.",
  MINUS = "Boosts SP.ATK with a PLUS ally.",
  NATURAL_CURE = "Heals status on switching out.",
  OBLIVIOUS = "Blocks charm and attract effects.",
  OVERGROW = "Powers up GRASS moves in a pinch.",
  OWN_TEMPO = "Prevents confusion.",
  PICKUP = "May find items after battle.",
  PLUS = "Boosts SP.ATK with a MINUS ally.",
  POISON_POINT = "Contact may poison the foe.",
  PRESSURE = "Makes foes spend more PP.",
  PURE_POWER = "Boosts physical ATTACK.",
  ROCK_HEAD = "Protects from recoil damage.",
  ROUGH_SKIN = "Hurts foes on contact.",
  RUN_AWAY = "Sure escape from wild battles.",
  SAND_STREAM = "Summons a sandstorm.",
  SAND_VEIL = "Boosts evasion in a sandstorm.",
  SERENE_GRACE = "Boosts the chance of added effects.",
  SHADOW_TAG = "Prevents the foe from fleeing.",
  SHED_SKIN = "May heal its own status.",
  SHELL_ARMOR = "Protects from critical hits.",
  SHIELD_DUST = "Blocks added move effects.",
  SOUNDPROOF = "Immune to sound moves.",
  SPEED_BOOST = "Raises SPEED each turn.",
  STATIC = "Contact may paralyze the foe.",
  STENCH = "May make the foe flinch.",
  STURDY = "Cannot be knocked out in one hit.",
  SUCTION_CUPS = "Firmly anchors the body.",
  SWARM = "Powers up BUG moves in a pinch.",
  SWIFT_SWIM = "Boosts SPEED in rain.",
  SYNCHRONIZE = "Passes status back to the foe.",
  THICK_FAT = "Resists FIRE and ICE moves.",
  TORRENT = "Powers up WATER moves in a pinch.",
  TRACE = "Copies the foe's ability.",
  TRUANT = "Can only attack every other turn.",
  VITAL_SPIRIT = "Prevents sleep.",
  VOLT_ABSORB = "Restores HP if hit by ELECTRIC.",
  WATER_ABSORB = "Restores HP if hit by WATER.",
  WATER_VEIL = "Prevents burns.",
  WHITE_SMOKE = "Prevents foes from lowering stats.",
  WONDER_GUARD = "Only super-effective hits land.",
}

function AbilityText.describe(id)
  if not id or id == "" or id == "NONE" then
    return "No special ability."
  end
  return AbilityText[id] or "A mysterious ability."
end

return AbilityText
