-- Generated breeding fields (PokéAPI egg groups / hatch / egg moves)
-- Applied onto Data.pokemon via pokemon:patch
local P = {}

P.species = {
  ABRA = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "ABRA",
    eggMoves = { "FIRE_PUNCH", "ICE_PUNCH", "THUNDERPUNCH", "CONFUSION", "BARRIER", "LIGHT_SCREEN", "ENCORE", "MAGIC_COAT", "KNOCK_OFF", "SKILL_SWAP", "PSYCHO_SHIFT", "POWER_TRICK", "GUARD_SWAP", "GUARD_SPLIT", "ALLY_SWITCH", "PSYCHIC_TERRAIN" },
  },
  ABSOL = {
    eggGroups = { "FIELD" },
    hatchCounter = 25,
    babySpecies = "ABSOL",
    eggMoves = { "DOUBLE_EDGE", "BITE", "SUBSTITUTE", "CURSE", "FEINT_ATTACK", "PERISH_SONG", "MEAN_LOOK", "MEGAHORN", "BATON_PASS", "MAGIC_COAT", "FEINT", "ASSURANCE", "ME_FIRST", "PUNISHMENT", "SUCKER_PUNCH", "ZEN_HEADBUTT", "HEX", "PLAY_ROUGH" },
  },
  AERODACTYL = {
    eggGroups = { "FLYING" },
    hatchCounter = 35,
    babySpecies = "AERODACTYL",
    eggMoves = { "WHIRLWIND", "CURSE", "FORESIGHT", "STEEL_WING", "DRAGON_BREATH", "PURSUIT", "ROOST", "TAILWIND", "ASSURANCE", "WIDE_GUARD" },
  },
  AGGRON = {
    eggGroups = { "MONSTER" },
    hatchCounter = 35,
    babySpecies = "ARON",
    evolvesFrom = "LAIRON",
    eggMoves = {  },
  },
  AIPOM = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "AIPOM",
    eggMoves = { "DOUBLESLAP", "SLAM", "COUNTER", "AGILITY", "SCREECH", "SPITE", "PURSUIT", "IRON_TAIL", "BEAT_UP", "FAKE_OUT", "REVENGE", "BOUNCE", "COVET", "SWITCHEROO", "QUICK_GUARD", "TAIL_SLAP" },
  },
  ALAKAZAM = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "ABRA",
    evolvesFrom = "KADABRA",
    eggMoves = {  },
  },
  ALTARIA = {
    eggGroups = { "FLYING", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "SWABLU",
    evolvesFrom = "SWABLU",
    eggMoves = {  },
  },
  AMPHAROS = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "MAREEP",
    evolvesFrom = "FLAAFFY",
    eggMoves = {  },
  },
  ANORITH = {
    eggGroups = { "WATER_3" },
    hatchCounter = 30,
    babySpecies = "ANORITH",
    eggMoves = { "SWORDS_DANCE", "SAND_ATTACK", "SCREECH", "ROCK_SLIDE", "CURSE", "RAPID_SPIN", "KNOCK_OFF", "IRON_DEFENSE", "WATER_PULSE", "CROSS_POISON", "AQUA_JET" },
  },
  ARBOK = {
    eggGroups = { "FIELD", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "EKANS",
    evolvesFrom = "EKANS",
    eggMoves = { "SPITE", "SCARY_FACE", "POISON_FANG", "POISON_TAIL", "SUCKER_PUNCH", "SWITCHEROO" },
  },
  ARCANINE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "GROWLITHE",
    evolvesFrom = "GROWLITHE",
    eggMoves = {  },
  },
  ARIADOS = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "SPINARAK",
    evolvesFrom = "SPINARAK",
    eggMoves = { "DISABLE", "MEGAHORN", "NIGHT_SLASH", "RAGE_POWDER", "LUNGE" },
  },
  ARMALDO = {
    eggGroups = { "WATER_3" },
    hatchCounter = 30,
    babySpecies = "ANORITH",
    evolvesFrom = "ANORITH",
    eggMoves = {  },
  },
  ARON = {
    eggGroups = { "MONSTER" },
    hatchCounter = 35,
    babySpecies = "ARON",
    eggMoves = { "STOMP", "BODY_SLAM", "SCREECH", "CURSE", "REVERSAL", "MUD_SLAP", "SMELLING_SALTS", "SUPERPOWER", "ENDEAVOR", "DRAGON_RUSH", "IRON_HEAD", "STEALTH_ROCK", "HEAD_SMASH" },
  },
  ARTICUNO = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "ARTICUNO",
    eggMoves = {  },
  },
  AZUMARILL = {
    eggGroups = { "WATER_1", "FAIRY" },
    hatchCounter = 10,
    babySpecies = "AZURILL",
    evolvesFrom = "MARILL",
    eggMoves = {  },
  },
  AZURILL = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 10,
    babySpecies = "AZURILL",
    eggMoves = { "SLAM", "BODY_SLAM", "SING", "SUPERSONIC", "BELLY_DRUM", "PERISH_SONG", "PRESENT", "ENCORE", "REFRESH", "CAMOUFLAGE", "FAKE_TEARS", "TICKLE", "MUDDY_WATER", "WATER_SPORT", "COPYCAT", "AQUA_JET", "SOAK" },
  },
  BAGON = {
    eggGroups = { "DRAGON" },
    hatchCounter = 40,
    babySpecies = "BAGON",
    eggMoves = { "THRASH", "HYDRO_PUMP", "DRAGON_RAGE", "DEFENSE_CURL", "ENDURE", "TWISTER", "DRAGON_DANCE", "DRAGON_PULSE", "DRAGON_RUSH", "SHADOW_CLAW", "FIRE_FANG" },
  },
  BALTOY = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "BALTOY",
    eggMoves = {  },
  },
  BANETTE = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "SHUPPET",
    evolvesFrom = "SHUPPET",
    eggMoves = {  },
  },
  BARBOACH = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "BARBOACH",
    eggMoves = { "TAKE_DOWN", "THRASH", "HYDRO_PUMP", "FLAIL", "SPARK", "WHIRLPOOL", "MUDDY_WATER", "MUD_SHOT", "DRAGON_DANCE", "EARTH_POWER" },
  },
  BAYLEEF = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 20,
    babySpecies = "CHIKORITA",
    evolvesFrom = "CHIKORITA",
    eggMoves = { "VINE_WHIP", "COUNTER", "FLAIL", "ANCIENT_POWER", "INGRAIN", "HEAL_PULSE" },
  },
  BEAUTIFLY = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WURMPLE",
    evolvesFrom = "SILCOON",
    eggMoves = {  },
  },
  BEEDRILL = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WEEDLE",
    evolvesFrom = "KAKUNA",
    eggMoves = {  },
  },
  BELDUM = {
    eggGroups = { "MINERAL" },
    hatchCounter = 40,
    babySpecies = "BELDUM",
    eggMoves = {  },
  },
  BELLOSSOM = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "ODDISH",
    evolvesFrom = "GLOOM",
    eggMoves = { "LEECH_SEED", "RAZOR_LEAF", "FLAIL", "SYNTHESIS", "INGRAIN", "TEETER_DANCE", "TICKLE", "AFTER_YOU", "STRENGTH_SAP" },
  },
  BELLSPROUT = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "BELLSPROUT",
    eggMoves = { "SWORDS_DANCE", "REFLECT", "LEECH_LIFE", "GIGA_DRAIN", "ENCORE", "SYNTHESIS", "INGRAIN", "WEATHER_BALL", "TICKLE", "BULLET_SEED", "MAGICAL_LEAF", "NATURAL_GIFT", "WORRY_SEED", "SUCKER_PUNCH", "POWER_WHIP", "ACID_SPRAY", "CLEAR_SMOG", "BELCH", "STRENGTH_SAP" },
  },
  BLASTOISE = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "SQUIRTLE",
    evolvesFrom = "WARTORTLE",
    eggMoves = { "MIST", "FLAIL", "MIRROR_COAT", "FAKE_OUT", "YAWN", "WATER_SPOUT", "AQUA_RING", "AQUA_JET", "LIFE_DEW" },
  },
  BLAZIKEN = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TORCHIC",
    evolvesFrom = "COMBUSKEN",
    eggMoves = { "FIRE_PUNCH", "EMBER", "FLAMETHROWER", "PECK", "COUNTER", "FEATHER_DANCE", "CRUSH_CLAW", "FEINT", "LAST_RESORT", "NIGHT_SLASH" },
  },
  BLISSEY = {
    eggGroups = { "FAIRY" },
    hatchCounter = 40,
    babySpecies = "HAPPINY",
    evolvesFrom = "CHANSEY",
    eggMoves = { "SEISMIC_TOSS", "HEAL_BELL", "PRESENT", "GRAVITY" },
  },
  BRELOOM = {
    eggGroups = { "FAIRY", "GRASS" },
    hatchCounter = 15,
    babySpecies = "SHROOMISH",
    evolvesFrom = "SHROOMISH",
    eggMoves = {  },
  },
  BULBASAUR = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 20,
    babySpecies = "BULBASAUR",
    eggMoves = { "RAZOR_WIND", "PETAL_DANCE", "TOXIC", "LIGHT_SCREEN", "SLUDGE", "SKULL_BASH", "AMNESIA", "CURSE", "GIGA_DRAIN", "ENDURE", "CHARM", "SAFEGUARD", "NATURE_POWER", "INGRAIN", "GRASS_WHISTLE", "MAGICAL_LEAF", "LEAF_STORM", "POWER_WHIP", "GRASSY_TERRAIN" },
  },
  BUTTERFREE = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "CATERPIE",
    evolvesFrom = "METAPOD",
    eggMoves = {  },
  },
  CACNEA = {
    eggGroups = { "GRASS", "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "CACNEA",
    eggMoves = { "DISABLE", "ACID", "LOW_KICK", "COUNTER", "DYNAMIC_PUNCH", "SMELLING_SALTS", "TEETER_DANCE", "GRASS_WHISTLE", "BLOCK", "MAGICAL_LEAF", "WORRY_SEED", "SEED_BOMB", "SWITCHEROO", "NASTY_PLOT", "BELCH", "ROTOTILLER", "FELL_STINGER", "POWER_UP_PUNCH" },
  },
  CACTURNE = {
    eggGroups = { "GRASS", "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "CACNEA",
    evolvesFrom = "CACNEA",
    eggMoves = {  },
  },
  CAMERUPT = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "NUMEL",
    evolvesFrom = "NUMEL",
    eggMoves = {  },
  },
  CARVANHA = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "CARVANHA",
    eggMoves = { "THRASH", "DOUBLE_EDGE", "HYDRO_PUMP", "SWIFT", "DESTINY_BOND", "ANCIENT_POWER", "WATER_PULSE", "BRINE", "PSYCHIC_FANGS" },
  },
  CASCOON = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WURMPLE",
    evolvesFrom = "WURMPLE",
    eggMoves = {  },
  },
  CASTFORM = {
    eggGroups = { "FAIRY", "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "CASTFORM",
    eggMoves = { "DISABLE", "AMNESIA", "PSYCH_UP", "FUTURE_SIGHT", "COSMIC_POWER", "LUCKY_CHANT", "GUARD_SWAP", "OMINOUS_WIND", "CLEAR_SMOG", "HEX", "REFLECT_TYPE" },
  },
  CATERPIE = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "CATERPIE",
    eggMoves = {  },
  },
  CELEBI = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "CELEBI",
    eggMoves = {  },
  },
  CHANSEY = {
    eggGroups = { "FAIRY" },
    hatchCounter = 40,
    babySpecies = "HAPPINY",
    evolvesFrom = "HAPPINY",
    eggMoves = { "COUNTER", "SEISMIC_TOSS", "METRONOME", "SUBSTITUTE", "ENDURE", "HEAL_BELL", "PRESENT", "HELPING_HAND", "AROMATHERAPY", "GRAVITY", "NATURAL_GIFT", "MUD_BOMB" },
  },
  CHARIZARD = {
    eggGroups = { "MONSTER", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "CHARMANDER",
    evolvesFrom = "CHARMELEON",
    eggMoves = { "BITE", "COUNTER", "BELLY_DRUM", "IRON_TAIL", "METAL_CLAW", "ANCIENT_POWER", "DRAGON_RUSH", "DRAGON_TAIL" },
  },
  CHARMANDER = {
    eggGroups = { "MONSTER", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "CHARMANDER",
    eggMoves = { "SWORDS_DANCE", "WING_ATTACK", "BITE", "COUNTER", "ROCK_SLIDE", "BELLY_DRUM", "OUTRAGE", "IRON_TAIL", "METAL_CLAW", "CRUNCH", "ANCIENT_POWER", "BEAT_UP", "FOCUS_PUNCH", "AIR_CUTTER", "DRAGON_DANCE", "FLARE_BLITZ", "DRAGON_PULSE", "DRAGON_RUSH", "DRAGON_TAIL" },
  },
  CHARMELEON = {
    eggGroups = { "MONSTER", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "CHARMANDER",
    evolvesFrom = "CHARMANDER",
    eggMoves = { "BITE", "COUNTER", "BELLY_DRUM", "IRON_TAIL", "METAL_CLAW", "ANCIENT_POWER", "DRAGON_RUSH", "DRAGON_TAIL" },
  },
  CHIKORITA = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 20,
    babySpecies = "CHIKORITA",
    eggMoves = { "SWORDS_DANCE", "VINE_WHIP", "BODY_SLAM", "COUNTER", "LEECH_SEED", "FLAIL", "ANCIENT_POWER", "NATURE_POWER", "INGRAIN", "REFRESH", "AROMATHERAPY", "GRASS_WHISTLE", "WRING_OUT", "LEAF_STORM", "HEAL_PULSE", "GRASSY_TERRAIN" },
  },
  CHIMECHO = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "CHINGLING",
    evolvesFrom = "CHINGLING",
    eggMoves = { "DISABLE", "HYPNOSIS", "RECOVER", "DREAM_EATER", "CURSE", "PERISH_SONG", "FUTURE_SIGHT", "WISH", "RECYCLE", "SKILL_SWAP", "COSMIC_POWER", "STORED_POWER", "ALLY_SWITCH", "CRAFTY_SHIELD" },
  },
  CHINCHOU = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "CHINCHOU",
    eggMoves = { "SUPERSONIC", "MIST", "PSYBEAM", "AGILITY", "SCREECH", "AMNESIA", "FLAIL", "WHIRLPOOL", "SHOCK_WAVE", "WATER_PULSE", "BRINE", "SUCKER_PUNCH", "SOAK" },
  },
  CLAMPERL = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "CLAMPERL",
    eggMoves = { "BODY_SLAM", "SUPERSONIC", "CONFUSE_RAY", "BARRIER", "ENDURE", "REFRESH", "MUD_SPORT", "MUDDY_WATER", "WATER_PULSE", "BRINE", "AQUA_RING" },
  },
  CLAYDOL = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "BALTOY",
    evolvesFrom = "BALTOY",
    eggMoves = {  },
  },
  CLEFABLE = {
    eggGroups = { "FAIRY" },
    hatchCounter = 10,
    babySpecies = "CLEFFA",
    evolvesFrom = "CLEFAIRY",
    eggMoves = { "POUND", "GROWL", "SING", "DEFENSE_CURL", "SPLASH", "SWEET_KISS", "CHARM", "PRESENT", "ENCORE", "MOONLIGHT", "FOLLOW_ME", "WISH", "TICKLE", "COSMIC_POWER", "GRAVITY", "HEALING_WISH", "COPYCAT", "AFTER_YOU", "STORED_POWER", "HEAL_PULSE", "DISARMING_VOICE" },
  },
  CLEFAIRY = {
    eggGroups = { "FAIRY" },
    hatchCounter = 10,
    babySpecies = "CLEFFA",
    evolvesFrom = "CLEFFA",
    eggMoves = { "PRESENT", "WISH", "TICKLE", "HEAL_PULSE" },
  },
  CLEFFA = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 10,
    babySpecies = "CLEFFA",
    eggMoves = { "MIMIC", "METRONOME", "AMNESIA", "SPLASH", "SUBSTITUTE", "BELLY_DRUM", "PRESENT", "WISH", "AROMATHERAPY", "FAKE_TEARS", "TICKLE", "COVET", "STORED_POWER", "HEAL_PULSE", "MISTY_TERRAIN" },
  },
  CLOYSTER = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "SHELLDER",
    evolvesFrom = "SHELLDER",
    eggMoves = {  },
  },
  COMBUSKEN = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TORCHIC",
    evolvesFrom = "TORCHIC",
    eggMoves = { "FLAMETHROWER", "PECK", "COUNTER", "FEATHER_DANCE", "CRUSH_CLAW", "FEINT", "LAST_RESORT", "NIGHT_SLASH" },
  },
  CORPHISH = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 15,
    babySpecies = "CORPHISH",
    eggMoves = { "BODY_SLAM", "DOUBLE_EDGE", "SLASH", "METAL_CLAW", "ANCIENT_POWER", "SUPERPOWER", "KNOCK_OFF", "ENDEAVOR", "MUD_SPORT", "DRAGON_DANCE", "TRUMP_CARD", "SWITCHEROO", "AQUA_JET", "CHIP_AWAY" },
  },
  CORSOLA = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 20,
    babySpecies = "CORSOLA",
    eggMoves = { "MIST", "SCREECH", "CONFUSE_RAY", "BARRIER", "BIDE", "AMNESIA", "ROCK_SLIDE", "CURSE", "SAFEGUARD", "NATURE_POWER", "INGRAIN", "CAMOUFLAGE", "ICICLE_SPEAR", "WATER_PULSE", "AQUA_RING", "HEAD_SMASH", "LIQUIDATION" },
  },
  CRADILY = {
    eggGroups = { "WATER_3" },
    hatchCounter = 30,
    babySpecies = "LILEEP",
    evolvesFrom = "LILEEP",
    eggMoves = {  },
  },
  CRAWDAUNT = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 15,
    babySpecies = "CORPHISH",
    evolvesFrom = "CORPHISH",
    eggMoves = { "DOUBLE_EDGE", "SLASH", "METAL_CLAW", "ANCIENT_POWER", "SWITCHEROO", "AQUA_JET" },
  },
  CROBAT = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "ZUBAT",
    evolvesFrom = "GOLBAT",
    eggMoves = {  },
  },
  CROCONAW = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "TOTODILE",
    evolvesFrom = "TOTODILE",
    eggMoves = { "COUNTER", "ANCIENT_POWER", "FLATTER", "BLOCK", "AQUA_JET" },
  },
  CUBONE = {
    eggGroups = { "MONSTER" },
    hatchCounter = 20,
    babySpecies = "CUBONE",
    eggMoves = { "SWORDS_DANCE", "DOUBLE_KICK", "LEER", "SCREECH", "SKULL_BASH", "ROCK_SLIDE", "CURSE", "BELLY_DRUM", "PERISH_SONG", "DETECT", "ENDURE", "ANCIENT_POWER", "IRON_HEAD", "CHIP_AWAY" },
  },
  CYNDAQUIL = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "CYNDAQUIL",
    eggMoves = { "DOUBLE_KICK", "THRASH", "DOUBLE_EDGE", "SUBMISSION", "QUICK_ATTACK", "FURY_SWIPES", "CURSE", "REVERSAL", "FORESIGHT", "NATURE_POWER", "CRUSH_CLAW", "EXTRASENSORY", "HOWL", "COVET", "FLARE_BLITZ", "FLAME_BURST" },
  },
  DELCATTY = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 15,
    babySpecies = "SKITTY",
    evolvesFrom = "SKITTY",
    eggMoves = {  },
  },
  DELIBIRD = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "DELIBIRD",
    eggMoves = { "ICE_PUNCH", "AURORA_BEAM", "COUNTER", "QUICK_ATTACK", "SPLASH", "SPIKES", "DESTINY_BOND", "ICY_WIND", "RAPID_SPIN", "FUTURE_SIGHT", "FAKE_OUT", "MEMENTO", "ICE_BALL", "ICE_SHARD", "BESTOW", "FREEZE_DRY", "AURORA_VEIL" },
  },
  DEOXYS = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "DEOXYS",
    eggMoves = {  },
  },
  DEWGONG = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "SEEL",
    evolvesFrom = "SEEL",
    eggMoves = { "HORN_DRILL", "DISABLE", "LICK", "PERISH_SONG", "FAKE_OUT", "STOCKPILE", "SPIT_UP", "SWALLOW", "ENTRAINMENT", "BELCH" },
  },
  DIGLETT = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "DIGLETT",
    eggMoves = { "HEADBUTT", "SCREECH", "ROCK_SLIDE", "REVERSAL", "FEINT_ATTACK", "ENDURE", "PURSUIT", "ANCIENT_POWER", "BEAT_UP", "UPROAR", "MEMENTO", "ASTONISH", "MUD_BOMB", "HONE_CLAWS", "FINAL_GAMBIT" },
  },
  DITTO = {
    eggGroups = { "DITTO" },
    hatchCounter = 20,
    babySpecies = "DITTO",
    eggMoves = {  },
  },
  DODRIO = {
    eggGroups = { "FLYING" },
    hatchCounter = 20,
    babySpecies = "DODUO",
    evolvesFrom = "DODUO",
    eggMoves = { "WHIRLWIND", "SKY_ATTACK", "FLAIL", "ASSURANCE" },
  },
  DODUO = {
    eggGroups = { "FLYING" },
    hatchCounter = 20,
    babySpecies = "DODUO",
    eggMoves = { "WHIRLWIND", "SUPERSONIC", "QUICK_ATTACK", "HAZE", "MIRROR_MOVE", "SKY_ATTACK", "FLAIL", "FEINT_ATTACK", "ENDEAVOR", "NATURAL_GIFT", "ASSURANCE", "BRAVE_BIRD" },
  },
  DONPHAN = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "PHANPY",
    evolvesFrom = "PHANPY",
    eggMoves = {  },
  },
  DRAGONAIR = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 40,
    babySpecies = "DRATINI",
    evolvesFrom = "DRATINI",
    eggMoves = {  },
  },
  DRAGONITE = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 40,
    babySpecies = "DRATINI",
    evolvesFrom = "DRAGONAIR",
    eggMoves = {  },
  },
  DRATINI = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 40,
    babySpecies = "DRATINI",
    eggMoves = { "SUPERSONIC", "MIST", "LIGHT_SCREEN", "HAZE", "DRAGON_BREATH", "IRON_TAIL", "EXTREME_SPEED", "DRAGON_DANCE", "WATER_PULSE", "DRAGON_PULSE", "DRAGON_RUSH", "AQUA_JET" },
  },
  DROWZEE = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "DROWZEE",
    eggMoves = { "FIRE_PUNCH", "ICE_PUNCH", "THUNDERPUNCH", "BARRIER", "LIGHT_SCREEN", "FLATTER", "ROLE_PLAY", "ASSIST", "SKILL_SWAP", "SECRET_POWER", "GUARD_SWAP", "NASTY_PLOT", "PSYCHO_CUT", "POWER_SPLIT", "PSYCHIC_TERRAIN" },
  },
  DUGTRIO = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "DIGLETT",
    evolvesFrom = "DIGLETT",
    eggMoves = {  },
  },
  DUNSPARCE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "DUNSPARCE",
    eggMoves = { "HEADBUTT", "BITE", "AGILITY", "RAGE", "BIDE", "ROCK_SLIDE", "SNORE", "CURSE", "SLEEP_TALK", "ANCIENT_POWER", "MAGIC_COAT", "SECRET_POWER", "ASTONISH", "TRUMP_CARD", "LAST_RESORT", "AQUA_TAIL", "HEX" },
  },
  DUSCLOPS = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "DUSKULL",
    evolvesFrom = "DUSKULL",
    eggMoves = { "HAZE", "PAIN_SPLIT", "MEMENTO" },
  },
  DUSKULL = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "DUSKULL",
    eggMoves = { "HAZE", "FEINT_ATTACK", "DESTINY_BOND", "PAIN_SPLIT", "MEMENTO", "SKILL_SWAP", "IMPRISON", "GRUDGE", "DARK_PULSE", "OMINOUS_WIND" },
  },
  DUSTOX = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WURMPLE",
    evolvesFrom = "CASCOON",
    eggMoves = {  },
  },
  EEVEE = {
    eggGroups = { "FIELD" },
    hatchCounter = 35,
    babySpecies = "EEVEE",
    eggMoves = { "DOUBLE_KICK", "CURSE", "FLAIL", "MUD_SLAP", "DETECT", "ENDURE", "CHARM", "WISH", "YAWN", "FAKE_TEARS", "TICKLE", "COVET", "NATURAL_GIFT", "CAPTIVATE", "SYNCHRONOISE", "STORED_POWER" },
  },
  EKANS = {
    eggGroups = { "FIELD", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "EKANS",
    eggMoves = { "SLAM", "DISABLE", "SPITE", "SCARY_FACE", "PURSUIT", "IRON_TAIL", "CRUNCH", "BEAT_UP", "SNATCH", "POISON_FANG", "POISON_TAIL", "SUCKER_PUNCH", "SWITCHEROO" },
  },
  ELECTABUZZ = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "ELEKID",
    evolvesFrom = "ELEKID",
    eggMoves = { "DYNAMIC_PUNCH", "CROSS_CHOP", "FOCUS_PUNCH", "FOLLOW_ME", "HAMMER_ARM", "FEINT" },
  },
  ELECTRIKE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "ELECTRIKE",
    eggMoves = { "HEADBUTT", "SWIFT", "CURSE", "SPARK", "CRUNCH", "UPROAR", "SHOCK_WAVE", "SWITCHEROO", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "DISCHARGE", "FLAME_BURST", "ELECTRO_BALL", "EERIE_IMPULSE" },
  },
  ELECTRODE = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "VOLTORB",
    evolvesFrom = "VOLTORB",
    eggMoves = {  },
  },
  ELEKID = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 25,
    babySpecies = "ELEKID",
    eggMoves = { "KARATE_CHOP", "FIRE_PUNCH", "ICE_PUNCH", "ROLLING_KICK", "MEDITATE", "BARRIER", "DYNAMIC_PUNCH", "CROSS_CHOP", "FOCUS_PUNCH", "FOLLOW_ME", "HAMMER_ARM", "FEINT" },
  },
  ENTEI = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "ENTEI",
    eggMoves = { "SACRED_FIRE", "EXTREME_SPEED" },
  },
  ESPEON = {
    eggGroups = { "FIELD" },
    hatchCounter = 35,
    babySpecies = "EEVEE",
    evolvesFrom = "EEVEE",
    eggMoves = {  },
  },
  EXEGGCUTE = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "EXEGGCUTE",
    eggMoves = { "MEGA_DRAIN", "POISONPOWDER", "STUN_SPORE", "SLEEP_POWDER", "REFLECT", "CURSE", "GIGA_DRAIN", "SYNTHESIS", "MOONLIGHT", "PSYCH_UP", "ANCIENT_POWER", "NATURE_POWER", "INGRAIN", "SKILL_SWAP", "BLOCK", "NATURAL_GIFT", "LUCKY_CHANT", "POWER_SWAP", "LEAF_STORM", "GRASSY_TERRAIN" },
  },
  EXEGGUTOR = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "EXEGGCUTE",
    evolvesFrom = "EXEGGCUTE",
    eggMoves = {  },
  },
  EXPLOUD = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "WHISMUR",
    evolvesFrom = "LOUDRED",
    eggMoves = {  },
  },
  FARFETCHD = {
    eggGroups = { "FLYING", "FIELD" },
    hatchCounter = 20,
    babySpecies = "FARFETCHD",
    eggMoves = { "GUST", "QUICK_ATTACK", "MIRROR_MOVE", "SKY_ATTACK", "CURSE", "FLAIL", "MUD_SLAP", "FORESIGHT", "STEEL_WING", "REVENGE", "FEATHER_DANCE", "COVET", "LEAF_BLADE", "ROOST", "FEINT", "TRUMP_CARD", "NIGHT_SLASH", "SIMPLE_BEAM", "FINAL_GAMBIT", "FIRST_IMPRESSION" },
  },
  FEAROW = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "SPEAROW",
    evolvesFrom = "SPEAROW",
    eggMoves = {  },
  },
  FEEBAS = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "FEEBAS",
    eggMoves = { "MIST", "HYPNOSIS", "CONFUSE_RAY", "LIGHT_SCREEN", "HAZE", "DRAGON_BREATH", "IRON_TAIL", "MIRROR_COAT", "MUD_SPORT", "TICKLE", "BRINE", "DRAGON_PULSE", "CAPTIVATE" },
  },
  FERALIGATR = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "TOTODILE",
    evolvesFrom = "CROCONAW",
    eggMoves = { "COUNTER", "ANCIENT_POWER", "FLATTER", "BLOCK", "AQUA_JET" },
  },
  FLAAFFY = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "MAREEP",
    evolvesFrom = "MAREEP",
    eggMoves = {  },
  },
  FLAREON = {
    eggGroups = { "FIELD" },
    hatchCounter = 35,
    babySpecies = "EEVEE",
    evolvesFrom = "EEVEE",
    eggMoves = {  },
  },
  FLYGON = {
    eggGroups = { "BUG", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "TRAPINCH",
    evolvesFrom = "VIBRAVA",
    eggMoves = { "GUST", "BITE", "FISSURE", "DIG", "QUICK_ATTACK", "FLAIL", "FURY_CUTTER", "CRUNCH", "SUPERPOWER", "ASTONISH", "DRAGON_DANCE", "FEINT", "BUG_BITE", "FIRST_IMPRESSION" },
  },
  FORRETRESS = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "PINECO",
    evolvesFrom = "PINECO",
    eggMoves = {  },
  },
  FURRET = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "SENTRET",
    evolvesFrom = "SENTRET",
    eggMoves = { "FOCUS_ENERGY", "SLASH", "REVERSAL", "LAST_RESORT", "BABY_DOLL_EYES", "TIDY_UP" },
  },
  GARDEVOIR = {
    eggGroups = { "HUMAN_LIKE", "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "RALTS",
    evolvesFrom = "KIRLIA",
    eggMoves = {  },
  },
  GASTLY = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GASTLY",
    eggMoves = { "FIRE_PUNCH", "ICE_PUNCH", "THUNDERPUNCH", "DISABLE", "TOXIC", "HAZE", "SMOG", "PSYWAVE", "EXPLOSION", "SCARY_FACE", "PERISH_SONG", "WILL_O_WISP", "GRUDGE", "ASTONISH", "CLEAR_SMOG", "REFLECT_TYPE" },
  },
  GENGAR = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GASTLY",
    evolvesFrom = "HAUNTER",
    eggMoves = {  },
  },
  GEODUDE = {
    eggGroups = { "MINERAL" },
    hatchCounter = 15,
    babySpecies = "GEODUDE",
    eggMoves = { "MEGA_PUNCH", "ROCK_SLIDE", "CURSE", "FLAIL", "ENDURE", "DYNAMIC_PUNCH", "FOCUS_PUNCH", "BLOCK", "HAMMER_ARM", "ROCK_CLIMB", "WIDE_GUARD", "AUTOTOMIZE" },
  },
  GIRAFARIG = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "GIRAFARIG",
    eggMoves = { "RAZOR_WIND", "DOUBLE_KICK", "TAKE_DOWN", "AMNESIA", "FORESIGHT", "MEAN_LOOK", "MIRROR_COAT", "PSYCH_UP", "FUTURE_SIGHT", "BEAT_UP", "UPROAR", "WISH", "MAGIC_COAT", "SKILL_SWAP", "SECRET_POWER", "ALLY_SWITCH", "PSYCHIC_TERRAIN", "PSYCHIC_FANGS" },
  },
  GLALIE = {
    eggGroups = { "FAIRY", "MINERAL" },
    hatchCounter = 20,
    babySpecies = "SNORUNT",
    evolvesFrom = "SNORUNT",
    eggMoves = {  },
  },
  GLIGAR = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "GLIGAR",
    eggMoves = { "RAZOR_WIND", "WING_ATTACK", "DOUBLE_EDGE", "COUNTER", "AGILITY", "BATON_PASS", "METAL_CLAW", "SAND_TOMB", "POISON_TAIL", "FEINT", "POWER_TRICK", "NIGHT_SLASH", "ROCK_CLIMB", "CROSS_POISON" },
  },
  GLOOM = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "ODDISH",
    evolvesFrom = "ODDISH",
    eggMoves = { "LEECH_SEED", "RAZOR_LEAF", "FLAIL", "SYNTHESIS", "INGRAIN", "TEETER_DANCE", "TICKLE", "AFTER_YOU", "STRENGTH_SAP" },
  },
  GOLBAT = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "ZUBAT",
    evolvesFrom = "ZUBAT",
    eggMoves = {  },
  },
  GOLDEEN = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "GOLDEEN",
    eggMoves = { "BODY_SLAM", "HYDRO_PUMP", "PSYBEAM", "HAZE", "SKULL_BASH", "MUD_SLAP", "SLEEP_TALK", "MUD_SPORT", "SIGNAL_BEAM", "MUD_SHOT", "ACUPRESSURE", "AQUA_TAIL" },
  },
  GOLDUCK = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "PSYDUCK",
    evolvesFrom = "PSYDUCK",
    eggMoves = {  },
  },
  GOLEM = {
    eggGroups = { "MINERAL" },
    hatchCounter = 15,
    babySpecies = "GEODUDE",
    evolvesFrom = "GRAVELER",
    eggMoves = { "MEGA_PUNCH", "CURSE", "FLAIL", "DYNAMIC_PUNCH", "BLOCK", "HAMMER_ARM", "WIDE_GUARD" },
  },
  GOREBYSS = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "CLAMPERL",
    evolvesFrom = "CLAMPERL",
    eggMoves = {  },
  },
  GRANBULL = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 20,
    babySpecies = "SNUBBULL",
    evolvesFrom = "SNUBBULL",
    eggMoves = { "COUNTER", "MIMIC", "SNORE", "PRESENT", "RETALIATE" },
  },
  GRAVELER = {
    eggGroups = { "MINERAL" },
    hatchCounter = 15,
    babySpecies = "GEODUDE",
    evolvesFrom = "GEODUDE",
    eggMoves = { "MEGA_PUNCH", "CURSE", "FLAIL", "DYNAMIC_PUNCH", "BLOCK", "HAMMER_ARM", "WIDE_GUARD" },
  },
  GRIMER = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GRIMER",
    eggMoves = { "HAZE", "LICK", "EXPLOSION", "CURSE", "SCARY_FACE", "MEAN_LOOK", "STOCKPILE", "SPIT_UP", "SWALLOW", "IMPRISON", "SHADOW_PUNCH", "SHADOW_SNEAK", "ACID_SPRAY", "POWER_UP_PUNCH" },
  },
  GROUDON = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "GROUDON",
    eggMoves = {  },
  },
  GROVYLE = {
    eggGroups = { "MONSTER", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "TREECKO",
    evolvesFrom = "TREECKO",
    eggMoves = { "DOUBLE_KICK", "ABSORB", "LEECH_SEED", "SLASH", "FALSE_SWIPE", "FURY_CUTTER", "DRAGON_BREATH", "SYNTHESIS", "WORRY_SEED", "NIGHT_SLASH", "X_SCISSOR", "ENERGY_BALL" },
  },
  GROWLITHE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "GROWLITHE",
    eggMoves = { "DOUBLE_KICK", "BODY_SLAM", "THRASH", "DOUBLE_EDGE", "FIRE_SPIN", "SAFEGUARD", "IRON_TAIL", "MORNING_SUN", "CRUNCH", "HEAT_WAVE", "HOWL", "COVET", "CLOSE_COMBAT", "FLARE_BLITZ", "BURN_UP", "RAGING_FURY" },
  },
  GRUMPIG = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SPOINK",
    evolvesFrom = "SPOINK",
    eggMoves = {  },
  },
  GULPIN = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GULPIN",
    eggMoves = { "SMOG", "DREAM_EATER", "ACID_ARMOR", "CURSE", "MUD_SLAP", "DESTINY_BOND", "PAIN_SPLIT", "GUNK_SHOT", "CLEAR_SMOG", "VENOM_DRENCH", "STUFF_CHEEKS" },
  },
  GYARADOS = {
    eggGroups = { "WATER_2", "DRAGON" },
    hatchCounter = 5,
    babySpecies = "MAGIKARP",
    evolvesFrom = "MAGIKARP",
    eggMoves = {  },
  },
  HARIYAMA = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MAKUHITA",
    evolvesFrom = "MAKUHITA",
    eggMoves = {  },
  },
  HAUNTER = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GASTLY",
    evolvesFrom = "GASTLY",
    eggMoves = {  },
  },
  HERACROSS = {
    eggGroups = { "BUG" },
    hatchCounter = 25,
    babySpecies = "HERACROSS",
    eggMoves = { "TAKE_DOWN", "DOUBLE_EDGE", "SEISMIC_TOSS", "HARDEN", "BIDE", "FLAIL", "FALSE_SWIPE", "MEGAHORN", "PURSUIT", "FOCUS_PUNCH", "REVENGE", "ROCK_BLAST", "FEINT", "NIGHT_SLASH" },
  },
  HITMONCHAN = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "TYROGUE",
    evolvesFrom = "TYROGUE",
    eggMoves = { "COUNTER", "HI_JUMP_KICK", "MACH_PUNCH", "RAPID_SPIN", "FEINT", "VACUUM_WAVE", "BULLET_PUNCH" },
  },
  HITMONLEE = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "TYROGUE",
    evolvesFrom = "TYROGUE",
    eggMoves = { "COUNTER", "HI_JUMP_KICK", "MACH_PUNCH", "RAPID_SPIN", "FEINT", "VACUUM_WAVE", "BULLET_PUNCH" },
  },
  HITMONTOP = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "TYROGUE",
    evolvesFrom = "TYROGUE",
    eggMoves = { "COUNTER", "HI_JUMP_KICK", "MACH_PUNCH", "RAPID_SPIN", "FEINT", "VACUUM_WAVE", "BULLET_PUNCH" },
  },
  HOOTHOOT = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "HOOTHOOT",
    eggMoves = { "WING_ATTACK", "WHIRLWIND", "SUPERSONIC", "AGILITY", "NIGHT_SHADE", "MIRROR_MOVE", "SKY_ATTACK", "FEINT_ATTACK", "MEAN_LOOK", "FEATHER_DANCE", "DEFOG", "HURRICANE" },
  },
  HOPPIP = {
    eggGroups = { "FAIRY", "GRASS" },
    hatchCounter = 20,
    babySpecies = "HOPPIP",
    eggMoves = { "PAY_DAY", "DOUBLE_EDGE", "GROWL", "CONFUSION", "REFLECT", "AMNESIA", "ENDURE", "ENCORE", "PSYCH_UP", "HELPING_HAND", "AROMATHERAPY", "WORRY_SEED", "SEED_BOMB", "SWITCHEROO", "RAGE_POWDER", "COTTON_GUARD", "GRASSY_TERRAIN", "STRENGTH_SAP" },
  },
  HORSEA = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "HORSEA",
    eggMoves = { "RAZOR_WIND", "DISABLE", "AURORA_BEAM", "DRAGON_RAGE", "SPLASH", "FLAIL", "OCTAZOOKA", "OUTRAGE", "DRAGON_BREATH", "SIGNAL_BEAM", "MUDDY_WATER", "WATER_PULSE", "CLEAR_SMOG" },
  },
  HOUNDOOM = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "HOUNDOUR",
    evolvesFrom = "HOUNDOUR",
    eggMoves = {  },
  },
  HOUNDOUR = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "HOUNDOUR",
    eggMoves = { "COUNTER", "FIRE_SPIN", "RAGE", "REVERSAL", "SPITE", "DESTINY_BOND", "PURSUIT", "BEAT_UP", "WILL_O_WISP", "FEINT", "PUNISHMENT", "SUCKER_PUNCH", "NASTY_PLOT", "THUNDER_FANG", "FIRE_FANG" },
  },
  HO_OH = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "HO_OH",
    eggMoves = {  },
  },
  HUNTAIL = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "CLAMPERL",
    evolvesFrom = "CLAMPERL",
    eggMoves = {  },
  },
  HYPNO = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "DROWZEE",
    evolvesFrom = "DROWZEE",
    eggMoves = {  },
  },
  IGGLYBUFF = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 10,
    babySpecies = "IGGLYBUFF",
    eggMoves = { "FEINT_ATTACK", "PERISH_SONG", "ROLLOUT", "SLEEP_TALK", "PRESENT", "WISH", "FAKE_TEARS", "COVET", "GRAVITY", "PUNISHMENT", "LAST_RESORT", "CAPTIVATE", "HEAL_PULSE", "MISTY_TERRAIN" },
  },
  ILLUMISE = {
    eggGroups = { "BUG", "HUMAN_LIKE" },
    hatchCounter = 15,
    babySpecies = "ILLUMISE",
    eggMoves = { "GROWTH", "CONFUSE_RAY", "ATTRACT", "BATON_PASS", "ENCORE", "AROMATHERAPY", "FAKE_TEARS", "SILVER_WIND", "ROOST", "BUG_BUZZ", "CAPTIVATE" },
  },
  IVYSAUR = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 20,
    babySpecies = "BULBASAUR",
    evolvesFrom = "BULBASAUR",
    eggMoves = { "PETAL_DANCE", "TOXIC", "CURSE", "INGRAIN" },
  },
  JIGGLYPUFF = {
    eggGroups = { "FAIRY" },
    hatchCounter = 10,
    babySpecies = "IGGLYBUFF",
    evolvesFrom = "IGGLYBUFF",
    eggMoves = {  },
  },
  JIRACHI = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "JIRACHI",
    eggMoves = {  },
  },
  JOLTEON = {
    eggGroups = { "FIELD" },
    hatchCounter = 35,
    babySpecies = "EEVEE",
    evolvesFrom = "EEVEE",
    eggMoves = {  },
  },
  JUMPLUFF = {
    eggGroups = { "FAIRY", "GRASS" },
    hatchCounter = 20,
    babySpecies = "HOPPIP",
    evolvesFrom = "SKIPLOOM",
    eggMoves = {  },
  },
  JYNX = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "SMOOCHUM",
    evolvesFrom = "SMOOCHUM",
    eggMoves = {  },
  },
  KABUTO = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 30,
    babySpecies = "KABUTO",
    eggMoves = { "TAKE_DOWN", "BUBBLEBEAM", "AURORA_BEAM", "MEGA_DRAIN", "DIG", "SCREECH", "CONFUSE_RAY", "FLAIL", "FORESIGHT", "ICY_WIND", "GIGA_DRAIN", "RAPID_SPIN", "KNOCK_OFF", "MUD_SHOT" },
  },
  KABUTOPS = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 30,
    babySpecies = "KABUTO",
    evolvesFrom = "KABUTO",
    eggMoves = {  },
  },
  KADABRA = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "ABRA",
    evolvesFrom = "ABRA",
    eggMoves = {  },
  },
  KAKUNA = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WEEDLE",
    evolvesFrom = "WEEDLE",
    eggMoves = {  },
  },
  KANGASKHAN = {
    eggGroups = { "MONSTER" },
    hatchCounter = 20,
    babySpecies = "KANGASKHAN",
    eggMoves = { "STOMP", "DOUBLE_EDGE", "DISABLE", "COUNTER", "FOCUS_ENERGY", "SUBSTITUTE", "FORESIGHT", "SAFEGUARD", "UPROAR", "FOCUS_PUNCH", "ENDEAVOR", "CRUSH_CLAW", "HAMMER_ARM", "TRUMP_CARD", "CIRCLE_THROW" },
  },
  KECLEON = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "KECLEON",
    eggMoves = { "DISABLE", "RECOVER", "DIZZY_PUNCH", "FAKE_OUT", "TRICK", "MAGIC_COAT", "SKILL_SWAP", "SNATCH", "CAMOUFLAGE", "NASTY_PLOT", "FOUL_PLAY", "POWER_UP_PUNCH" },
  },
  KINGDRA = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "HORSEA",
    evolvesFrom = "SEADRA",
    eggMoves = { "DISABLE", "AURORA_BEAM", "SPLASH", "FLAIL", "CLEAR_SMOG" },
  },
  KINGLER = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "KRABBY",
    evolvesFrom = "KRABBY",
    eggMoves = {  },
  },
  KIRLIA = {
    eggGroups = { "HUMAN_LIKE", "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "RALTS",
    evolvesFrom = "RALTS",
    eggMoves = {  },
  },
  KOFFING = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "KOFFING",
    eggMoves = { "PSYBEAM", "SCREECH", "PSYWAVE", "CURSE", "SPITE", "DESTINY_BOND", "PAIN_SPLIT", "STOCKPILE", "SPIT_UP", "SWALLOW", "WILL_O_WISP", "GRUDGE", "TOXIC_SPIKES", "VENOM_DRENCH" },
  },
  KRABBY = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "KRABBY",
    eggMoves = { "SWORDS_DANCE", "SLAM", "DIG", "AGILITY", "HAZE", "BIDE", "AMNESIA", "SLASH", "FLAIL", "ENDURE", "ANCIENT_POWER", "KNOCK_OFF", "TICKLE", "HAMMER_ARM", "NIGHT_SLASH", "CHIP_AWAY", "ALLY_SWITCH" },
  },
  KYOGRE = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "KYOGRE",
    eggMoves = {  },
  },
  LAIRON = {
    eggGroups = { "MONSTER" },
    hatchCounter = 35,
    babySpecies = "ARON",
    evolvesFrom = "ARON",
    eggMoves = {  },
  },
  LANTURN = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "CHINCHOU",
    evolvesFrom = "CHINCHOU",
    eggMoves = { "MIST", "PSYBEAM", "WATER_PULSE", "SUCKER_PUNCH", "SOAK" },
  },
  LAPRAS = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 40,
    babySpecies = "LAPRAS",
    eggMoves = { "HORN_DRILL", "AURORA_BEAM", "FISSURE", "SUBSTITUTE", "CURSE", "FORESIGHT", "SLEEP_TALK", "ANCIENT_POWER", "FUTURE_SIGHT", "WHIRLPOOL", "REFRESH", "TICKLE", "DRAGON_DANCE", "DRAGON_PULSE", "AVALANCHE", "FREEZE_DRY", "SPARKLING_ARIA" },
  },
  LARVITAR = {
    eggGroups = { "MONSTER" },
    hatchCounter = 40,
    babySpecies = "LARVITAR",
    eggMoves = { "STOMP", "FOCUS_ENERGY", "CURSE", "OUTRAGE", "PURSUIT", "IRON_TAIL", "ANCIENT_POWER", "IRON_DEFENSE", "DRAGON_DANCE", "ASSURANCE", "IRON_HEAD", "STEALTH_ROCK" },
  },
  LATIAS = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "LATIAS",
    eggMoves = {  },
  },
  LATIOS = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "LATIOS",
    eggMoves = {  },
  },
  LEDIAN = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "LEDYBA",
    evolvesFrom = "LEDYBA",
    eggMoves = {  },
  },
  LEDYBA = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "LEDYBA",
    eggMoves = { "PSYBEAM", "COUNTER", "SCREECH", "LIGHT_SCREEN", "BIDE", "DIZZY_PUNCH", "ENDURE", "ENCORE", "FOCUS_PUNCH", "KNOCK_OFF", "SILVER_WIND", "TAILWIND", "BUG_BUZZ", "DRAIN_PUNCH", "BUG_BITE" },
  },
  LICKITUNG = {
    eggGroups = { "MONSTER" },
    hatchCounter = 20,
    babySpecies = "LICKITUNG",
    eggMoves = { "BODY_SLAM", "THRASH", "AMNESIA", "SUBSTITUTE", "SNORE", "CURSE", "BELLY_DRUM", "SLEEP_TALK", "MAGNITUDE", "SMELLING_SALTS", "MUDDY_WATER", "HAMMER_ARM", "ZEN_HEADBUTT", "BELCH" },
  },
  LILEEP = {
    eggGroups = { "WATER_3" },
    hatchCounter = 30,
    babySpecies = "LILEEP",
    eggMoves = { "BIND", "MEGA_DRAIN", "RECOVER", "BARRIER", "ROCK_SLIDE", "CURSE", "ENDURE", "MIRROR_COAT", "TICKLE", "WRING_OUT", "STEALTH_ROCK" },
  },
  LINOONE = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "ZIGZAGOON",
    evolvesFrom = "ZIGZAGOON",
    eggMoves = {  },
  },
  LOMBRE = {
    eggGroups = { "WATER_1", "GRASS" },
    hatchCounter = 15,
    babySpecies = "LOTAD",
    evolvesFrom = "LOTAD",
    eggMoves = { "COUNTER", "RAZOR_LEAF", "SWEET_SCENT", "SYNTHESIS", "TEETER_DANCE", "TICKLE" },
  },
  LOTAD = {
    eggGroups = { "WATER_1", "GRASS" },
    hatchCounter = 15,
    babySpecies = "LOTAD",
    eggMoves = { "WATER_GUN", "COUNTER", "LEECH_SEED", "RAZOR_LEAF", "FLAIL", "GIGA_DRAIN", "SWEET_SCENT", "SYNTHESIS", "TEETER_DANCE", "TICKLE" },
  },
  LOUDRED = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "WHISMUR",
    evolvesFrom = "WHISMUR",
    eggMoves = {  },
  },
  LUDICOLO = {
    eggGroups = { "WATER_1", "GRASS" },
    hatchCounter = 15,
    babySpecies = "LOTAD",
    evolvesFrom = "LOMBRE",
    eggMoves = { "GROWL", "MIST", "WATER_GUN", "HYDRO_PUMP", "COUNTER", "ABSORB", "MEGA_DRAIN", "RAZOR_LEAF", "FURY_SWIPES", "FLAIL", "SWEET_SCENT", "SYNTHESIS", "KNOCK_OFF", "TEETER_DANCE", "ASTONISH", "TICKLE", "ENERGY_BALL", "ZEN_HEADBUTT" },
  },
  LUGIA = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "LUGIA",
    eggMoves = { "DRAGON_RUSH" },
  },
  LUNATONE = {
    eggGroups = { "MINERAL" },
    hatchCounter = 25,
    babySpecies = "LUNATONE",
    eggMoves = {  },
  },
  LUVDISC = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "LUVDISC",
    eggMoves = { "SUPERSONIC", "SPLASH", "MUD_SPORT", "WATER_SPORT", "BRINE", "AQUA_RING", "CAPTIVATE", "AQUA_JET", "ENTRAINMENT", "HEAL_PULSE" },
  },
  MACHAMP = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MACHOP",
    evolvesFrom = "MACHOKE",
    eggMoves = {  },
  },
  MACHOKE = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MACHOP",
    evolvesFrom = "MACHOP",
    eggMoves = {  },
  },
  MACHOP = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MACHOP",
    eggMoves = { "FIRE_PUNCH", "ICE_PUNCH", "THUNDERPUNCH", "ROLLING_KICK", "SUBMISSION", "COUNTER", "MEDITATE", "LIGHT_SCREEN", "ROCK_SLIDE", "ENCORE", "SMELLING_SALTS", "KNOCK_OFF", "TICKLE", "CLOSE_COMBAT", "POWER_TRICK", "BULLET_PUNCH", "HEAVY_SLAM", "QUICK_GUARD" },
  },
  MAGBY = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 25,
    babySpecies = "MAGBY",
    eggMoves = { "KARATE_CHOP", "MEGA_PUNCH", "THUNDERPUNCH", "SCREECH", "BARRIER", "FOCUS_ENERGY", "MACH_PUNCH", "BELLY_DRUM", "DYNAMIC_PUNCH", "IRON_TAIL", "CROSS_CHOP", "FOCUS_PUNCH", "FOLLOW_ME", "POWER_SWAP", "FLARE_BLITZ", "BELCH" },
  },
  MAGCARGO = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "SLUGMA",
    evolvesFrom = "SLUGMA",
    eggMoves = { "SMOKESCREEN", "ACID_ARMOR", "CURSE", "ROLLOUT", "STOCKPILE", "MEMENTO", "GUARD_SWAP", "INFERNO" },
  },
  MAGIKARP = {
    eggGroups = { "WATER_2", "DRAGON" },
    hatchCounter = 5,
    babySpecies = "MAGIKARP",
    eggMoves = {  },
  },
  MAGMAR = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "MAGBY",
    evolvesFrom = "MAGBY",
    eggMoves = { "MACH_PUNCH", "BELLY_DRUM", "DYNAMIC_PUNCH", "CROSS_CHOP", "FOCUS_PUNCH", "FOLLOW_ME", "BELCH" },
  },
  MAGNEMITE = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "MAGNEMITE",
    eggMoves = { "EXPLOSION", "ELECTROWEB" },
  },
  MAGNETON = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "MAGNEMITE",
    evolvesFrom = "MAGNEMITE",
    eggMoves = {  },
  },
  MAKUHITA = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MAKUHITA",
    eggMoves = { "COUNTER", "FEINT_ATTACK", "FORESIGHT", "DETECT", "DYNAMIC_PUNCH", "CROSS_CHOP", "FOCUS_PUNCH", "HELPING_HAND", "REVENGE", "WAKE_UP_SLAP", "FEINT", "BULLET_PUNCH", "WIDE_GUARD", "CHIP_AWAY" },
  },
  MANECTRIC = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "ELECTRIKE",
    evolvesFrom = "ELECTRIKE",
    eggMoves = {  },
  },
  MANKEY = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "MANKEY",
    eggMoves = { "COUNTER", "MEDITATE", "ROCK_SLIDE", "CURSE", "REVERSAL", "SPITE", "FORESIGHT", "SLEEP_TALK", "ENCORE", "BEAT_UP", "FOCUS_PUNCH", "SMELLING_SALTS", "REVENGE", "CLOSE_COMBAT", "NIGHT_SLASH", "POWER_TRIP" },
  },
  MANTINE = {
    eggGroups = { "WATER_1" },
    hatchCounter = 25,
    babySpecies = "MANTYKE",
    evolvesFrom = "MANTYKE",
    eggMoves = { "SLAM", "HYDRO_PUMP", "CONFUSE_RAY", "HAZE", "AMNESIA", "SPLASH", "ROCK_SLIDE", "TWISTER", "MIRROR_COAT", "MUD_SPORT", "WATER_SPORT", "TAILWIND", "WIDE_GUARD" },
  },
  MAREEP = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "MAREEP",
    eggMoves = { "SAND_ATTACK", "BODY_SLAM", "TAKE_DOWN", "THUNDERBOLT", "AGILITY", "SCREECH", "REFLECT", "SAFEGUARD", "IRON_TAIL", "FLATTER", "CHARGE", "ODOR_SLEUTH", "AFTER_YOU", "ELECTROWEB", "EERIE_IMPULSE", "ELECTRIC_TERRAIN" },
  },
  MARILL = {
    eggGroups = { "WATER_1", "FAIRY" },
    hatchCounter = 10,
    babySpecies = "AZURILL",
    evolvesFrom = "AZURILL",
    eggMoves = { "BODY_SLAM", "SING", "SUPERSONIC", "LIGHT_SCREEN", "AMNESIA", "SUBSTITUTE", "BELLY_DRUM", "FORESIGHT", "PERISH_SONG", "PRESENT", "FUTURE_SIGHT", "SUPERPOWER", "REFRESH", "CAMOUFLAGE", "TICKLE", "MUDDY_WATER", "WATER_SPORT", "COPYCAT", "AQUA_JET", "SOAK" },
  },
  MAROWAK = {
    eggGroups = { "MONSTER" },
    hatchCounter = 20,
    babySpecies = "CUBONE",
    evolvesFrom = "CUBONE",
    eggMoves = {  },
  },
  MARSHTOMP = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "MUDKIP",
    evolvesFrom = "MUDKIP",
    eggMoves = { "STOMP", "DOUBLE_EDGE", "BITE", "COUNTER", "SLUDGE", "CURSE", "MUD_SLAP", "MIRROR_COAT", "ANCIENT_POWER", "ROCK_SMASH", "YAWN", "WIDE_GUARD" },
  },
  MASQUERAIN = {
    eggGroups = { "WATER_1", "BUG" },
    hatchCounter = 15,
    babySpecies = "SURSKIT",
    evolvesFrom = "SURSKIT",
    eggMoves = {  },
  },
  MAWILE = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 20,
    babySpecies = "MAWILE",
    eggMoves = { "SWORDS_DANCE", "SLAM", "SEISMIC_TOSS", "FALSE_SWIPE", "PSYCH_UP", "ANCIENT_POWER", "POISON_FANG", "TICKLE", "METAL_BURST", "GUARD_SWAP", "PUNISHMENT", "SUCKER_PUNCH", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "CAPTIVATE", "MISTY_TERRAIN", "POWER_UP_PUNCH" },
  },
  MEDICHAM = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MEDITITE",
    evolvesFrom = "MEDITITE",
    eggMoves = {  },
  },
  MEDITITE = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 20,
    babySpecies = "MEDITITE",
    eggMoves = { "FIRE_PUNCH", "ICE_PUNCH", "THUNDERPUNCH", "FORESIGHT", "DYNAMIC_PUNCH", "BATON_PASS", "FAKE_OUT", "SECRET_POWER", "POWER_SWAP", "GUARD_SWAP", "DRAIN_PUNCH", "BULLET_PUNCH", "PSYCHO_CUT", "QUICK_GUARD" },
  },
  MEGANIUM = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 20,
    babySpecies = "CHIKORITA",
    evolvesFrom = "BAYLEEF",
    eggMoves = { "VINE_WHIP", "COUNTER", "FLAIL", "ANCIENT_POWER", "INGRAIN", "HEAL_PULSE" },
  },
  MEOWTH = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "MEOWTH",
    eggMoves = { "TAIL_WHIP", "HYPNOSIS", "AMNESIA", "FLAIL", "SPITE", "CHARM", "IRON_TAIL", "PSYCH_UP", "ASSIST", "SNATCH", "ODOR_SLEUTH", "COVET", "PUNISHMENT", "LAST_RESORT", "FOUL_PLAY" },
  },
  METAGROSS = {
    eggGroups = { "MINERAL" },
    hatchCounter = 40,
    babySpecies = "BELDUM",
    evolvesFrom = "METANG",
    eggMoves = { "EXPLOSION", "HONE_CLAWS" },
  },
  METANG = {
    eggGroups = { "MINERAL" },
    hatchCounter = 40,
    babySpecies = "BELDUM",
    evolvesFrom = "BELDUM",
    eggMoves = {  },
  },
  METAPOD = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "CATERPIE",
    evolvesFrom = "CATERPIE",
    eggMoves = {  },
  },
  MEW = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "MEW",
    eggMoves = {  },
  },
  MEWTWO = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "MEWTWO",
    eggMoves = {  },
  },
  MIGHTYENA = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "POOCHYENA",
    evolvesFrom = "POOCHYENA",
    eggMoves = { "POISON_FANG", "ASTONISH", "COVET" },
  },
  MILOTIC = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "FEEBAS",
    evolvesFrom = "FEEBAS",
    eggMoves = { "MIST", "HYPNOSIS", "CONFUSE_RAY", "HAZE", "DRAGON_BREATH", "MIRROR_COAT", "TICKLE" },
  },
  MILTANK = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "MILTANK",
    eggMoves = { "DOUBLE_EDGE", "SEISMIC_TOSS", "DIZZY_PUNCH", "CURSE", "REVERSAL", "ENDURE", "SLEEP_TALK", "PRESENT", "PSYCH_UP", "FOCUS_PUNCH", "HELPING_HAND", "HAMMER_ARM", "NATURAL_GIFT", "PUNISHMENT", "HEART_STAMP", "BELCH" },
  },
  MINUN = {
    eggGroups = { "FAIRY" },
    hatchCounter = 20,
    babySpecies = "MINUN",
    eggMoves = { "SING", "SUBSTITUTE", "SWEET_KISS", "CHARM", "WISH", "FAKE_TEARS", "LUCKY_CHANT", "DISCHARGE", "NUZZLE", "TEARFUL_LOOK" },
  },
  MISDREAVUS = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "MISDREAVUS",
    eggMoves = { "SCREECH", "CURSE", "SPITE", "DESTINY_BOND", "PSYCH_UP", "MEMENTO", "SKILL_SWAP", "IMPRISON", "ME_FIRST", "SUCKER_PUNCH", "NASTY_PLOT", "SHADOW_SNEAK", "OMINOUS_WIND", "WONDER_ROOM" },
  },
  MOLTRES = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "MOLTRES",
    eggMoves = {  },
  },
  MR_MIME = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "MIME_JR",
    evolvesFrom = "MIME_JR",
    eggMoves = { "HYPNOSIS", "MIMIC", "CONFUSE_RAY", "ICY_WIND", "PSYCH_UP", "FUTURE_SIGHT", "FAKE_OUT", "TRICK", "TEETER_DANCE", "TICKLE", "WAKE_UP_SLAP", "NASTY_PLOT", "POWER_SPLIT", "MAGIC_ROOM", "PSYCHIC_TERRAIN" },
  },
  MUDKIP = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "MUDKIP",
    eggMoves = { "STOMP", "DOUBLE_EDGE", "BITE", "COUNTER", "BARRIER", "SLUDGE", "CURSE", "MUD_SLAP", "MIRROR_COAT", "ANCIENT_POWER", "WHIRLPOOL", "UPROAR", "YAWN", "REFRESH", "ICE_BALL", "AVALANCHE", "MUD_BOMB", "WIDE_GUARD" },
  },
  MUK = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GRIMER",
    evolvesFrom = "GRIMER",
    eggMoves = {  },
  },
  MURKROW = {
    eggGroups = { "FLYING" },
    hatchCounter = 20,
    babySpecies = "MURKROW",
    eggMoves = { "WING_ATTACK", "WHIRLWIND", "DRILL_PECK", "QUICK_ATTACK", "SCREECH", "CONFUSE_RAY", "MIRROR_MOVE", "SKY_ATTACK", "FEINT_ATTACK", "PERISH_SONG", "FLATTER", "FEATHER_DANCE", "ROOST", "ASSURANCE", "PSYCHO_SHIFT", "PUNISHMENT", "BRAVE_BIRD" },
  },
  NATU = {
    eggGroups = { "FLYING" },
    hatchCounter = 20,
    babySpecies = "NATU",
    eggMoves = { "DRILL_PECK", "QUICK_ATTACK", "HAZE", "FEINT_ATTACK", "STEEL_WING", "PSYCH_UP", "SKILL_SWAP", "REFRESH", "FEATHER_DANCE", "ROOST", "SUCKER_PUNCH", "ZEN_HEADBUTT", "SYNCHRONOISE", "SIMPLE_BEAM", "ALLY_SWITCH" },
  },
  NIDOKING = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "NIDORAN_M",
    evolvesFrom = "NIDORINO",
    eggMoves = {  },
  },
  NIDOQUEEN = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 20,
    babySpecies = "NIDORAN_F",
    evolvesFrom = "NIDORINA",
    eggMoves = {  },
  },
  NIDORAN_F = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "NIDORAN_F",
    eggMoves = { "TAKE_DOWN", "SUPERSONIC", "DISABLE", "COUNTER", "FOCUS_ENERGY", "SKULL_BASH", "ENDURE", "CHARM", "PURSUIT", "IRON_TAIL", "BEAT_UP", "POISON_FANG", "POISON_TAIL", "CHIP_AWAY", "VENOM_DRENCH" },
  },
  NIDORAN_M = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "NIDORAN_M",
    eggMoves = { "HORN_DRILL", "TAKE_DOWN", "THRASH", "SUPERSONIC", "DISABLE", "COUNTER", "CONFUSION", "AMNESIA", "ENDURE", "IRON_TAIL", "BEAT_UP", "POISON_TAIL", "SUCKER_PUNCH", "HEAD_SMASH", "CHIP_AWAY", "VENOM_DRENCH" },
  },
  NIDORINA = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 20,
    babySpecies = "NIDORAN_F",
    evolvesFrom = "NIDORAN_F",
    eggMoves = {  },
  },
  NIDORINO = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "NIDORAN_M",
    evolvesFrom = "NIDORAN_M",
    eggMoves = {  },
  },
  NINCADA = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "NINCADA",
    eggMoves = { "GUST", "FLAIL", "FEINT_ATTACK", "ENDURE", "SILVER_WIND", "NIGHT_SLASH", "BUG_BUZZ", "BUG_BITE", "FINAL_GAMBIT" },
  },
  NINETALES = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "VULPIX",
    evolvesFrom = "VULPIX",
    eggMoves = { "ROAR", "HYPNOSIS", "FLAIL", "MEMENTO", "HOWL", "HEALING_WISH", "FLAME_CHARGE", "BABY_DOLL_EYES" },
  },
  NINJASK = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "NINCADA",
    evolvesFrom = "NINCADA",
    eggMoves = {  },
  },
  NOCTOWL = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "HOOTHOOT",
    evolvesFrom = "HOOTHOOT",
    eggMoves = { "WING_ATTACK", "WHIRLWIND", "SUPERSONIC", "NIGHT_SHADE", "FEATHER_DANCE" },
  },
  NOSEPASS = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "NOSEPASS",
    eggMoves = { "DOUBLE_EDGE", "EXPLOSION", "ENDURE", "ROLLOUT", "MAGNITUDE", "BLOCK", "STEALTH_ROCK", "HEAD_SMASH", "WIDE_GUARD" },
  },
  NUMEL = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "NUMEL",
    eggMoves = { "STOMP", "BODY_SLAM", "GROWTH", "DEFENSE_CURL", "SCARY_FACE", "ENDURE", "ROLLOUT", "ANCIENT_POWER", "STOCKPILE", "SPIT_UP", "SWALLOW", "HEAT_WAVE", "YAWN", "HOWL", "MUD_BOMB", "IRON_HEAD", "HEAVY_SLAM" },
  },
  NUZLEAF = {
    eggGroups = { "FIELD", "GRASS" },
    hatchCounter = 15,
    babySpecies = "SEEDOT",
    evolvesFrom = "SEEDOT",
    eggMoves = { "TAKE_DOWN", "LEECH_SEED", "QUICK_ATTACK", "WORRY_SEED", "NIGHT_SLASH", "DEFOG" },
  },
  OCTILLERY = {
    eggGroups = { "WATER_1", "WATER_2" },
    hatchCounter = 20,
    babySpecies = "REMORAID",
    evolvesFrom = "REMORAID",
    eggMoves = {  },
  },
  ODDISH = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "ODDISH",
    eggMoves = { "SWORDS_DANCE", "LEECH_SEED", "RAZOR_LEAF", "FLAIL", "CHARM", "SYNTHESIS", "NATURE_POWER", "INGRAIN", "SECRET_POWER", "TEETER_DANCE", "TICKLE", "AFTER_YOU", "STRENGTH_SAP" },
  },
  OMANYTE = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 30,
    babySpecies = "OMANYTE",
    eggMoves = { "SLAM", "BITE", "SUPERSONIC", "BUBBLEBEAM", "AURORA_BEAM", "HAZE", "BIDE", "ROCK_SLIDE", "SPIKES", "WHIRLPOOL", "KNOCK_OFF", "TICKLE", "MUDDY_WATER", "WATER_PULSE", "WRING_OUT", "TOXIC_SPIKES", "REFLECT_TYPE" },
  },
  OMASTAR = {
    eggGroups = { "WATER_1", "WATER_3" },
    hatchCounter = 30,
    babySpecies = "OMANYTE",
    evolvesFrom = "OMANYTE",
    eggMoves = {  },
  },
  ONIX = {
    eggGroups = { "MINERAL" },
    hatchCounter = 25,
    babySpecies = "ONIX",
    eggMoves = { "DEFENSE_CURL", "EXPLOSION", "ROCK_SLIDE", "FLAIL", "ROLLOUT", "BLOCK", "ROCK_BLAST", "ROCK_CLIMB", "STEALTH_ROCK", "HEAD_SMASH", "WIDE_GUARD", "HEAVY_SLAM", "DRAGON_TAIL", "ROTOTILLER" },
  },
  PARAS = {
    eggGroups = { "BUG", "GRASS" },
    hatchCounter = 20,
    babySpecies = "PARAS",
    eggMoves = { "PSYBEAM", "COUNTER", "LEECH_SEED", "AGILITY", "SCREECH", "LIGHT_SCREEN", "FLAIL", "ENDURE", "FALSE_SWIPE", "PURSUIT", "SWEET_SCENT", "METAL_CLAW", "NATURAL_GIFT", "CROSS_POISON", "BUG_BITE", "WIDE_GUARD", "ROTOTILLER", "FELL_STINGER", "GRASSY_TERRAIN" },
  },
  PARASECT = {
    eggGroups = { "BUG", "GRASS" },
    hatchCounter = 20,
    babySpecies = "PARAS",
    evolvesFrom = "PARAS",
    eggMoves = {  },
  },
  PELIPPER = {
    eggGroups = { "WATER_1", "FLYING" },
    hatchCounter = 20,
    babySpecies = "WINGULL",
    evolvesFrom = "WINGULL",
    eggMoves = { "WIDE_GUARD" },
  },
  PERSIAN = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "MEOWTH",
    evolvesFrom = "MEOWTH",
    eggMoves = {  },
  },
  PHANPY = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "PHANPY",
    eggMoves = { "BODY_SLAM", "WATER_GUN", "COUNTER", "FISSURE", "FOCUS_ENERGY", "SNORE", "MUD_SLAP", "ANCIENT_POWER", "ENDEAVOR", "ICE_SHARD", "HEAD_SMASH", "HEAVY_SLAM", "PLAY_ROUGH", "HIGH_HORSEPOWER" },
  },
  PICHU = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 10,
    babySpecies = "PICHU",
    eggMoves = { "DOUBLESLAP", "THUNDERPUNCH", "BIDE", "FLAIL", "REVERSAL", "ENDURE", "PRESENT", "ENCORE", "FAKE_OUT", "CHARGE", "WISH", "TICKLE", "LUCKY_CHANT", "BESTOW", "DISARMING_VOICE", "ELECTRIC_TERRAIN" },
  },
  PIDGEOT = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "PIDGEY",
    evolvesFrom = "PIDGEOTTO",
    eggMoves = {  },
  },
  PIDGEOTTO = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "PIDGEY",
    evolvesFrom = "PIDGEY",
    eggMoves = {  },
  },
  PIDGEY = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "PIDGEY",
    eggMoves = { "FEINT_ATTACK", "FORESIGHT", "STEEL_WING", "PURSUIT", "UPROAR", "AIR_CUTTER", "AIR_SLASH", "BRAVE_BIRD", "DEFOG" },
  },
  PIKACHU = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 10,
    babySpecies = "PICHU",
    evolvesFrom = "PICHU",
    eggMoves = {  },
  },
  PILOSWINE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SWINUB",
    evolvesFrom = "SWINUB",
    eggMoves = { "DOUBLE_EDGE", "BITE", "FISSURE", "CURSE", "ANCIENT_POWER", "ICICLE_CRASH", "FREEZE_DRY" },
  },
  PINECO = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "PINECO",
    eggMoves = { "DOUBLE_EDGE", "PIN_MISSILE", "COUNTER", "REFLECT", "SWIFT", "FLAIL", "ENDURE", "REVENGE", "SAND_TOMB", "POWER_TRICK", "TOXIC_SPIKES", "STEALTH_ROCK" },
  },
  PINSIR = {
    eggGroups = { "BUG" },
    hatchCounter = 25,
    babySpecies = "PINSIR",
    eggMoves = { "FURY_ATTACK", "THRASH", "QUICK_ATTACK", "FLAIL", "FEINT_ATTACK", "FALSE_SWIPE", "SUPERPOWER", "FEINT", "CLOSE_COMBAT", "ME_FIRST", "BUG_BITE" },
  },
  PLUSLE = {
    eggGroups = { "FAIRY" },
    hatchCounter = 20,
    babySpecies = "PLUSLE",
    eggMoves = { "SING", "SUBSTITUTE", "SWEET_KISS", "CHARM", "WISH", "FAKE_TEARS", "LUCKY_CHANT", "DISCHARGE", "NUZZLE", "TEARFUL_LOOK" },
  },
  POLITOED = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "POLIWAG",
    evolvesFrom = "POLIWHIRL",
    eggMoves = { "BODY_SLAM", "DOUBLE_EDGE", "MIST", "WATER_GUN", "BUBBLEBEAM", "HYPNOSIS", "SPLASH", "PERISH_SONG", "SWAGGER", "ENDEAVOR", "HYPER_VOICE", "MUDDY_WATER", "MUD_SHOT", "WATER_PULSE", "EARTH_POWER" },
  },
  POLIWAG = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "POLIWAG",
    eggMoves = { "MIST", "BUBBLEBEAM", "HAZE", "SPLASH", "MIND_READER", "ENDURE", "ENCORE", "ENDEAVOR", "REFRESH", "ICE_BALL", "MUDDY_WATER", "MUD_SHOT", "WATER_SPORT", "WATER_PULSE" },
  },
  POLIWHIRL = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "POLIWAG",
    evolvesFrom = "POLIWAG",
    eggMoves = { "MIST", "SPLASH", "ENDEAVOR", "MUDDY_WATER", "WATER_PULSE" },
  },
  POLIWRATH = {
    eggGroups = { "WATER_1" },
    hatchCounter = 20,
    babySpecies = "POLIWAG",
    evolvesFrom = "POLIWHIRL",
    eggMoves = { "POUND", "DOUBLE_EDGE", "MIST", "WATER_GUN", "HYDRO_PUMP", "SPLASH", "BELLY_DRUM", "RAIN_DANCE", "ENDEAVOR", "MUDDY_WATER", "MUD_SHOT", "WATER_PULSE", "EARTH_POWER", "CIRCLE_THROW" },
  },
  PONYTA = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "PONYTA",
    eggMoves = { "DOUBLE_KICK", "HORN_DRILL", "THRASH", "DOUBLE_EDGE", "LOW_KICK", "HYPNOSIS", "QUICK_ATTACK", "FLAME_WHEEL", "CHARM", "MORNING_SUN", "CAPTIVATE", "ALLY_SWITCH", "HIGH_HORSEPOWER" },
  },
  POOCHYENA = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "POOCHYENA",
    eggMoves = { "LEER", "SLEEP_TALK", "YAWN", "SNATCH", "POISON_FANG", "ASTONISH", "COVET", "ME_FIRST", "SUCKER_PUNCH", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "PLAY_ROUGH" },
  },
  PORYGON = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "PORYGON",
    eggMoves = {  },
  },
  PORYGON2 = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "PORYGON",
    evolvesFrom = "PORYGON",
    eggMoves = {  },
  },
  PRIMEAPE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "MANKEY",
    evolvesFrom = "MANKEY",
    eggMoves = {  },
  },
  PSYDUCK = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "PSYDUCK",
    eggMoves = { "ICE_BEAM", "PSYBEAM", "PSYCHIC_M", "HYPNOSIS", "CONFUSE_RAY", "LIGHT_SCREEN", "FORESIGHT", "SLEEP_TALK", "ENCORE", "CROSS_CHOP", "FUTURE_SIGHT", "YAWN", "REFRESH", "SECRET_POWER", "MUD_BOMB", "SYNCHRONOISE", "SIMPLE_BEAM", "CLEAR_SMOG" },
  },
  PUPITAR = {
    eggGroups = { "MONSTER" },
    hatchCounter = 40,
    babySpecies = "LARVITAR",
    evolvesFrom = "LARVITAR",
    eggMoves = {  },
  },
  QUAGSIRE = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "WOOPER",
    evolvesFrom = "WOOPER",
    eggMoves = {  },
  },
  QUILAVA = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "CYNDAQUIL",
    evolvesFrom = "CYNDAQUIL",
    eggMoves = { "DOUBLE_KICK", "CURSE", "REVERSAL", "EXTRASENSORY", "HOWL", "COVET" },
  },
  QWILFISH = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "QWILFISH",
    eggMoves = { "SUPERSONIC", "BUBBLEBEAM", "HAZE", "SELFDESTRUCT", "FLAIL", "ASTONISH", "SIGNAL_BEAM", "WATER_PULSE", "BRINE", "POISON_JAB", "AQUA_JET", "ACID_SPRAY", "BARB_BARRAGE" },
  },
  RAICHU = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 10,
    babySpecies = "PICHU",
    evolvesFrom = "PIKACHU",
    eggMoves = {  },
  },
  RAIKOU = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "RAIKOU",
    eggMoves = {  },
  },
  RALTS = {
    eggGroups = { "HUMAN_LIKE", "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "RALTS",
    eggMoves = { "DISABLE", "CONFUSE_RAY", "DESTINY_BOND", "MEAN_LOOK", "ENCORE", "WILL_O_WISP", "MEMENTO", "KNOCK_OFF", "SKILL_SWAP", "GRUDGE", "SHADOW_SNEAK", "SYNCHRONOISE", "ALLY_SWITCH", "MISTY_TERRAIN", "MYSTICAL_FIRE" },
  },
  RAPIDASH = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "PONYTA",
    evolvesFrom = "PONYTA",
    eggMoves = {  },
  },
  RATICATE = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "RATTATA",
    evolvesFrom = "RATTATA",
    eggMoves = {  },
  },
  RATTATA = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "RATTATA",
    eggMoves = { "BITE", "COUNTER", "SCREECH", "FURY_SWIPES", "FLAME_WHEEL", "REVERSAL", "SWAGGER", "UPROAR", "REVENGE", "ME_FIRST", "LAST_RESORT", "FINAL_GAMBIT" },
  },
  RAYQUAZA = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 120,
    babySpecies = "RAYQUAZA",
    eggMoves = {  },
  },
  REGICE = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "REGICE",
    eggMoves = {  },
  },
  REGIROCK = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "REGIROCK",
    eggMoves = {  },
  },
  REGISTEEL = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "REGISTEEL",
    eggMoves = {  },
  },
  RELICANTH = {
    eggGroups = { "WATER_1", "WATER_2" },
    hatchCounter = 40,
    babySpecies = "RELICANTH",
    eggMoves = { "SKULL_BASH", "AMNESIA", "ROCK_SLIDE", "SNORE", "MUD_SLAP", "SLEEP_TALK", "MAGNITUDE", "MUDDY_WATER", "MUD_SHOT", "WATER_SPORT", "BRINE", "AQUA_TAIL", "ZEN_HEADBUTT" },
  },
  REMORAID = {
    eggGroups = { "WATER_1", "WATER_2" },
    hatchCounter = 20,
    babySpecies = "REMORAID",
    eggMoves = { "SUPERSONIC", "AURORA_BEAM", "THUNDER_WAVE", "SCREECH", "HAZE", "SWIFT", "SNORE", "FLAIL", "OCTAZOOKA", "WATER_SPOUT", "MUD_SHOT", "ROCK_BLAST", "WATER_PULSE", "ACID_SPRAY", "ENTRAINMENT" },
  },
  RHYDON = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "RHYHORN",
    evolvesFrom = "RHYHORN",
    eggMoves = { "COUNTER", "CURSE", "METAL_BURST", "ROCK_POLISH", "DRAGON_RUSH", "GUARD_SPLIT" },
  },
  RHYHORN = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "RHYHORN",
    eggMoves = { "SWORDS_DANCE", "THRASH", "COUNTER", "SKULL_BASH", "ROCK_SLIDE", "CURSE", "REVERSAL", "MAGNITUDE", "PURSUIT", "IRON_TAIL", "CRUNCH", "CRUSH_CLAW", "METAL_BURST", "ROCK_POLISH", "DRAGON_RUSH", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "ROCK_CLIMB", "GUARD_SPLIT", "ROTOTILLER" },
  },
  ROSELIA = {
    eggGroups = { "FAIRY", "GRASS" },
    hatchCounter = 20,
    babySpecies = "BUDEW",
    evolvesFrom = "BUDEW",
    eggMoves = { "PIN_MISSILE", "RAZOR_LEAF", "SLEEP_POWDER", "MIND_READER", "COTTON_SPORE", "SPIKES", "GIGA_DRAIN", "SYNTHESIS", "GRASS_WHISTLE", "EXTRASENSORY", "BULLET_SEED", "NATURAL_GIFT", "SEED_BOMB", "LEAF_STORM", "POWER_WHIP", "LIFE_DEW" },
  },
  SABLEYE = {
    eggGroups = { "HUMAN_LIKE" },
    hatchCounter = 25,
    babySpecies = "SABLEYE",
    eggMoves = { "RECOVER", "MEAN_LOOK", "MOONLIGHT", "PSYCH_UP", "TORMENT", "FLATTER", "TRICK", "IMPRISON", "FEINT", "METAL_BURST", "SUCKER_PUNCH", "NASTY_PLOT", "CAPTIVATE" },
  },
  SALAMENCE = {
    eggGroups = { "DRAGON" },
    hatchCounter = 40,
    babySpecies = "BAGON",
    evolvesFrom = "SHELGON",
    eggMoves = {  },
  },
  SANDSHREW = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SANDSHREW",
    eggMoves = { "SWORDS_DANCE", "COUNTER", "ROCK_SLIDE", "FLAIL", "MUD_SLAP", "ENDURE", "SAFEGUARD", "RAPID_SPIN", "METAL_CLAW", "CRUSH_CLAW", "MUD_SHOT", "NIGHT_SLASH", "ROCK_CLIMB", "HONE_CLAWS", "CHIP_AWAY", "ROTOTILLER" },
  },
  SANDSLASH = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SANDSHREW",
    evolvesFrom = "SANDSHREW",
    eggMoves = { "COUNTER", "FLAIL", "MUD_SLAP", "METAL_CLAW", "NIGHT_SLASH", "HONE_CLAWS" },
  },
  SCEPTILE = {
    eggGroups = { "MONSTER", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "TREECKO",
    evolvesFrom = "GROVYLE",
    eggMoves = { "DOUBLE_KICK", "ABSORB", "LEECH_SEED", "SLASH", "FALSE_SWIPE", "FURY_CUTTER", "DRAGON_BREATH", "SYNTHESIS", "WORRY_SEED", "NIGHT_SLASH", "X_SCISSOR", "ENERGY_BALL", "SHED_TAIL" },
  },
  SCIZOR = {
    eggGroups = { "BUG" },
    hatchCounter = 25,
    babySpecies = "SCYTHER",
    evolvesFrom = "SCYTHER",
    eggMoves = {  },
  },
  SCYTHER = {
    eggGroups = { "BUG" },
    hatchCounter = 25,
    babySpecies = "SCYTHER",
    eggMoves = { "RAZOR_WIND", "COUNTER", "LIGHT_SCREEN", "REVERSAL", "ENDURE", "STEEL_WING", "SAFEGUARD", "BATON_PASS", "SILVER_WIND", "FEINT", "NIGHT_SLASH", "BUG_BUZZ", "DEFOG", "QUICK_GUARD" },
  },
  SEADRA = {
    eggGroups = { "WATER_1", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "HORSEA",
    evolvesFrom = "HORSEA",
    eggMoves = { "DISABLE", "AURORA_BEAM", "SPLASH", "FLAIL", "CLEAR_SMOG" },
  },
  SEAKING = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "GOLDEEN",
    evolvesFrom = "GOLDEEN",
    eggMoves = {  },
  },
  SEALEO = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "SPHEAL",
    evolvesFrom = "SPHEAL",
    eggMoves = {  },
  },
  SEEDOT = {
    eggGroups = { "FIELD", "GRASS" },
    hatchCounter = 15,
    babySpecies = "SEEDOT",
    eggMoves = { "RAZOR_WIND", "TAKE_DOWN", "LEECH_SEED", "QUICK_ATTACK", "AMNESIA", "FALSE_SWIPE", "BEAT_UP", "BULLET_SEED", "POWER_SWAP", "WORRY_SEED", "NIGHT_SLASH", "NASTY_PLOT", "DEFOG", "FOUL_PLAY", "GRASSY_TERRAIN" },
  },
  SEEL = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "SEEL",
    eggMoves = { "SLAM", "HORN_DRILL", "DISABLE", "PECK", "LICK", "PERISH_SONG", "SLEEP_TALK", "ENCORE", "IRON_TAIL", "FAKE_OUT", "STOCKPILE", "SPIT_UP", "SWALLOW", "SIGNAL_BEAM", "ICICLE_SPEAR", "WATER_PULSE", "ENTRAINMENT", "BELCH" },
  },
  SENTRET = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "SENTRET",
    eggMoves = { "DOUBLE_EDGE", "FOCUS_ENERGY", "SLASH", "SUBSTITUTE", "REVERSAL", "CHARM", "PURSUIT", "IRON_TAIL", "TRICK", "ASSIST", "COVET", "NATURAL_GIFT", "LAST_RESORT", "CAPTIVATE", "BABY_DOLL_EYES", "TIDY_UP" },
  },
  SEVIPER = {
    eggGroups = { "FIELD", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "SEVIPER",
    eggMoves = { "BODY_SLAM", "SCARY_FACE", "IRON_TAIL", "STOCKPILE", "SPIT_UP", "SWALLOW", "ASSURANCE", "WRING_OUT", "PUNISHMENT", "NIGHT_SLASH", "SWITCHEROO", "FINAL_GAMBIT" },
  },
  SHARPEDO = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "CARVANHA",
    evolvesFrom = "CARVANHA",
    eggMoves = {  },
  },
  SHEDINJA = {
    eggGroups = { "MINERAL" },
    hatchCounter = 15,
    babySpecies = "NINCADA",
    evolvesFrom = "NINCADA",
    eggMoves = {  },
  },
  SHELGON = {
    eggGroups = { "DRAGON" },
    hatchCounter = 40,
    babySpecies = "BAGON",
    evolvesFrom = "BAGON",
    eggMoves = {  },
  },
  SHELLDER = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "SHELLDER",
    eggMoves = { "TAKE_DOWN", "TWINEEDLE", "BUBBLEBEAM", "SCREECH", "BARRIER", "RAPID_SPIN", "ICICLE_SPEAR", "MUD_SHOT", "ROCK_BLAST", "WATER_PULSE", "AQUA_RING", "AVALANCHE", "LIFE_DEW" },
  },
  SHIFTRY = {
    eggGroups = { "FIELD", "GRASS" },
    hatchCounter = 15,
    babySpecies = "SEEDOT",
    evolvesFrom = "NUZLEAF",
    eggMoves = { "WHIRLWIND", "TACKLE", "TAKE_DOWN", "ABSORB", "MEGA_DRAIN", "LEECH_SEED", "GROWTH", "RAZOR_LEAF", "QUICK_ATTACK", "HARDEN", "EXPLOSION", "ROLLOUT", "SWAGGER", "SYNTHESIS", "BEAT_UP", "FAKE_OUT", "TORMENT", "ASTONISH", "EXTRASENSORY", "WORRY_SEED", "SUCKER_PUNCH", "NIGHT_SLASH", "DEFOG" },
  },
  SHROOMISH = {
    eggGroups = { "FAIRY", "GRASS" },
    hatchCounter = 15,
    babySpecies = "SHROOMISH",
    eggMoves = { "CHARM", "FALSE_SWIPE", "SWAGGER", "FOCUS_PUNCH", "HELPING_HAND", "FAKE_TEARS", "BULLET_SEED", "WAKE_UP_SLAP", "NATURAL_GIFT", "WORRY_SEED", "SEED_BOMB", "DRAIN_PUNCH" },
  },
  SHUCKLE = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "SHUCKLE",
    eggMoves = { "ACID", "TOXIC", "DEFENSE_CURL", "MUD_SLAP", "SWEET_SCENT", "HELPING_HAND", "KNOCK_OFF", "SAND_TOMB", "COVET", "ROCK_BLAST", "ACUPRESSURE", "FINAL_GAMBIT", "INFESTATION" },
  },
  SHUPPET = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 25,
    babySpecies = "SHUPPET",
    eggMoves = { "DISABLE", "CONFUSE_RAY", "FORESIGHT", "DESTINY_BOND", "PURSUIT", "IMPRISON", "ASTONISH", "PAYBACK", "SHADOW_SNEAK", "GUNK_SHOT", "OMINOUS_WIND", "PHANTOM_FORCE" },
  },
  SILCOON = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WURMPLE",
    evolvesFrom = "WURMPLE",
    eggMoves = {  },
  },
  SKARMORY = {
    eggGroups = { "FLYING" },
    hatchCounter = 25,
    babySpecies = "SKARMORY",
    eggMoves = { "WHIRLWIND", "DRILL_PECK", "SKY_ATTACK", "CURSE", "ENDURE", "PURSUIT", "AIR_CUTTER", "ROOST", "FEINT", "ASSURANCE", "GUARD_SWAP", "NIGHT_SLASH", "BRAVE_BIRD", "STEALTH_ROCK" },
  },
  SKIPLOOM = {
    eggGroups = { "FAIRY", "GRASS" },
    hatchCounter = 20,
    babySpecies = "HOPPIP",
    evolvesFrom = "HOPPIP",
    eggMoves = {  },
  },
  SKITTY = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 15,
    babySpecies = "SKITTY",
    eggMoves = { "SUBSTITUTE", "BATON_PASS", "PSYCH_UP", "FAKE_OUT", "UPROAR", "HELPING_HAND", "WISH", "FAKE_TEARS", "TICKLE", "COSMIC_POWER", "LAST_RESORT", "SUCKER_PUNCH", "MUD_BOMB", "ZEN_HEADBUTT", "CAPTIVATE", "SIMPLE_BEAM" },
  },
  SLAKING = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "SLAKOTH",
    evolvesFrom = "VIGOROTH",
    eggMoves = {  },
  },
  SLAKOTH = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "SLAKOTH",
    eggMoves = { "BODY_SLAM", "SLASH", "SNORE", "CURSE", "SLEEP_TALK", "PURSUIT", "CRUSH_CLAW", "TICKLE", "HAMMER_ARM", "NIGHT_SLASH", "AFTER_YOU" },
  },
  SLOWBRO = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "SLOWPOKE",
    evolvesFrom = "SLOWPOKE",
    eggMoves = { "FUTURE_SIGHT" },
  },
  SLOWKING = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "SLOWPOKE",
    evolvesFrom = "SLOWPOKE",
    eggMoves = { "FUTURE_SIGHT", "CHILLY_RECEPTION" },
  },
  SLOWPOKE = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "SLOWPOKE",
    eggMoves = { "STOMP", "SNORE", "BELLY_DRUM", "SLEEP_TALK", "SAFEGUARD", "FUTURE_SIGHT", "MUD_SPORT", "BLOCK", "ME_FIRST", "ZEN_HEADBUTT", "WONDER_ROOM", "BELCH" },
  },
  SLUGMA = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "SLUGMA",
    eggMoves = { "SMOKESCREEN", "ACID_ARMOR", "CURSE", "ROLLOUT", "STOCKPILE", "SPIT_UP", "SWALLOW", "HEAT_WAVE", "MEMENTO", "GUARD_SWAP", "EARTH_POWER", "INFERNO" },
  },
  SMEARGLE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SMEARGLE",
    eggMoves = {  },
  },
  SMOOCHUM = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 25,
    babySpecies = "SMOOCHUM",
    eggMoves = { "ICE_PUNCH", "MEDITATE", "LOVELY_KISS", "PSYCH_UP", "FAKE_OUT", "ROLE_PLAY", "WISH", "MIRACLE_EYE", "WAKE_UP_SLAP", "NASTY_PLOT", "CAPTIVATE" },
  },
  SNEASEL = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SNEASEL",
    eggMoves = { "ICE_PUNCH", "BITE", "COUNTER", "REFLECT", "SPITE", "FORESIGHT", "PURSUIT", "FAKE_OUT", "ASSIST", "CRUSH_CLAW", "FEINT", "PUNISHMENT", "AVALANCHE", "ICE_SHARD", "DOUBLE_HIT", "ICICLE_CRASH", "THROAT_CHOP" },
  },
  SNORLAX = {
    eggGroups = { "MONSTER" },
    hatchCounter = 40,
    babySpecies = "MUNCHLAX",
    evolvesFrom = "MUNCHLAX",
    eggMoves = { "WHIRLWIND", "DOUBLE_EDGE", "COUNTER", "FISSURE", "LICK", "SUBSTITUTE", "CURSE", "CHARM", "PURSUIT", "NATURAL_GIFT", "GASTRO_ACID", "AFTER_YOU", "BELCH", "POWER_UP_PUNCH" },
  },
  SNORUNT = {
    eggGroups = { "FAIRY", "MINERAL" },
    hatchCounter = 20,
    babySpecies = "SNORUNT",
    eggMoves = { "DISABLE", "BIDE", "SPIKES", "ROLLOUT", "WEATHER_BALL", "FAKE_TEARS", "BLOCK", "SWITCHEROO", "AVALANCHE", "HEX", "ICICLE_CRASH" },
  },
  SNUBBULL = {
    eggGroups = { "FIELD", "FAIRY" },
    hatchCounter = 20,
    babySpecies = "SNUBBULL",
    eggMoves = { "DOUBLE_EDGE", "LEER", "COUNTER", "MIMIC", "REFLECT", "METRONOME", "LICK", "SNORE", "FEINT_ATTACK", "HEAL_BELL", "PRESENT", "CRUNCH", "FOCUS_PUNCH", "SMELLING_SALTS", "FAKE_TEARS", "CLOSE_COMBAT", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "RETALIATE" },
  },
  SOLROCK = {
    eggGroups = { "MINERAL" },
    hatchCounter = 25,
    babySpecies = "SOLROCK",
    eggMoves = {  },
  },
  SPEAROW = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "SPEAROW",
    eggMoves = { "RAZOR_WIND", "WHIRLWIND", "QUICK_ATTACK", "SKY_ATTACK", "TRI_ATTACK", "SCARY_FACE", "FEINT_ATTACK", "FALSE_SWIPE", "STEEL_WING", "UPROAR", "FEATHER_DANCE", "ASTONISH" },
  },
  SPHEAL = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "SPHEAL",
    eggMoves = { "FISSURE", "ROCK_SLIDE", "CURSE", "BELLY_DRUM", "ROLLOUT", "SLEEP_TALK", "STOCKPILE", "SPIT_UP", "SWALLOW", "YAWN", "SIGNAL_BEAM", "WATER_SPORT", "WATER_PULSE", "AQUA_RING" },
  },
  SPINARAK = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "SPINARAK",
    eggMoves = { "TWINEEDLE", "SONICBOOM", "DISABLE", "PSYBEAM", "MEGAHORN", "BATON_PASS", "PURSUIT", "SIGNAL_BEAM", "TOXIC_SPIKES", "POISON_JAB", "NIGHT_SLASH", "RAGE_POWDER", "ELECTROWEB", "LUNGE" },
  },
  SPINDA = {
    eggGroups = { "FIELD", "HUMAN_LIKE" },
    hatchCounter = 15,
    babySpecies = "SPINDA",
    eggMoves = { "DISABLE", "ROCK_SLIDE", "ICY_WIND", "BATON_PASS", "ENCORE", "RAPID_SPIN", "FAKE_OUT", "SMELLING_SALTS", "TRICK", "ROLE_PLAY", "WISH", "ASSIST", "FAKE_TEARS", "WATER_PULSE", "PSYCHO_SHIFT", "PSYCHO_CUT", "GUARD_SPLIT", "SPOTLIGHT" },
  },
  SPOINK = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SPOINK",
    eggMoves = { "WHIRLWIND", "AMNESIA", "SUBSTITUTE", "ENDURE", "MIRROR_COAT", "FUTURE_SIGHT", "TRICK", "SKILL_SWAP", "EXTRASENSORY", "LUCKY_CHANT", "ZEN_HEADBUTT", "SIMPLE_BEAM" },
  },
  SQUIRTLE = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "SQUIRTLE",
    eggMoves = { "MIST", "CONFUSION", "HAZE", "FLAIL", "FORESIGHT", "MIRROR_COAT", "FAKE_OUT", "YAWN", "REFRESH", "MUD_SPORT", "WATER_SPOUT", "MUDDY_WATER", "BRINE", "AQUA_RING", "AURA_SPHERE", "DRAGON_PULSE", "AQUA_JET", "LIFE_DEW" },
  },
  STANTLER = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "STANTLER",
    eggMoves = { "DOUBLE_KICK", "THRASH", "BITE", "DISABLE", "RAGE", "LIGHT_SCREEN", "REFLECT", "SPITE", "SWAGGER", "MEGAHORN", "PSYCH_UP", "MUD_SPORT", "EXTRASENSORY", "ME_FIRST", "ZEN_HEADBUTT", "PSYSHIELD_BASH" },
  },
  STARMIE = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "STARYU",
    evolvesFrom = "STARYU",
    eggMoves = {  },
  },
  STARYU = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "STARYU",
    eggMoves = { "SUPERSONIC", "AURORA_BEAM", "BARRIER" },
  },
  STEELIX = {
    eggGroups = { "MINERAL" },
    hatchCounter = 25,
    babySpecies = "ONIX",
    evolvesFrom = "ONIX",
    eggMoves = {  },
  },
  SUDOWOODO = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "BONSLY",
    evolvesFrom = "BONSLY",
    eggMoves = { "HEADBUTT", "HARDEN", "DEFENSE_CURL", "SELFDESTRUCT", "CURSE", "ENDURE", "ROLLOUT", "SAND_TOMB", "ROCK_POLISH", "STEALTH_ROCK" },
  },
  SUICUNE = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "SUICUNE",
    eggMoves = { "EXTREME_SPEED", "SHEER_COLD" },
  },
  SUNFLORA = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "SUNKERN",
    evolvesFrom = "SUNKERN",
    eggMoves = {  },
  },
  SUNKERN = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "SUNKERN",
    eggMoves = { "LEECH_SEED", "BIDE", "CURSE", "ENDURE", "ENCORE", "SWEET_SCENT", "MORNING_SUN", "NATURE_POWER", "HELPING_HAND", "INGRAIN", "GRASS_WHISTLE", "NATURAL_GIFT", "GRASSY_TERRAIN" },
  },
  SURSKIT = {
    eggGroups = { "WATER_1", "BUG" },
    hatchCounter = 15,
    babySpecies = "SURSKIT",
    eggMoves = { "HYDRO_PUMP", "PSYBEAM", "MIND_READER", "FORESIGHT", "ENDURE", "SIGNAL_BEAM", "MUD_SHOT", "BUG_BITE", "AQUA_JET", "POWER_SPLIT", "FELL_STINGER", "LUNGE" },
  },
  SWABLU = {
    eggGroups = { "FLYING", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "SWABLU",
    eggMoves = { "AGILITY", "RAGE", "HAZE", "STEEL_WING", "PURSUIT", "FEATHER_DANCE", "HYPER_VOICE", "ASTONISH", "ROOST", "TAILWIND", "POWER_SWAP", "DRAGON_RUSH", "DEFOG", "PLAY_ROUGH" },
  },
  SWALOT = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "GULPIN",
    evolvesFrom = "GULPIN",
    eggMoves = {  },
  },
  SWAMPERT = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "MUDKIP",
    evolvesFrom = "MARSHTOMP",
    eggMoves = { "STOMP", "DOUBLE_EDGE", "BITE", "SURF", "COUNTER", "EARTHQUAKE", "SLUDGE", "CURSE", "MUD_SLAP", "MIRROR_COAT", "ANCIENT_POWER", "ROCK_SMASH", "YAWN", "HAMMER_ARM", "WIDE_GUARD" },
  },
  SWELLOW = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "TAILLOW",
    evolvesFrom = "TAILLOW",
    eggMoves = {  },
  },
  SWINUB = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "SWINUB",
    eggMoves = { "BODY_SLAM", "TAKE_DOWN", "DOUBLE_EDGE", "BITE", "FISSURE", "ROCK_SLIDE", "CURSE", "ANCIENT_POWER", "ICICLE_SPEAR", "MUD_SHOT", "AVALANCHE", "STEALTH_ROCK", "ICICLE_CRASH", "FREEZE_DRY" },
  },
  TAILLOW = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "TAILLOW",
    eggMoves = { "WHIRLWIND", "SUPERSONIC", "RAGE", "MIRROR_MOVE", "SKY_ATTACK", "STEEL_WING", "PURSUIT", "REFRESH", "ROOST", "BRAVE_BIRD", "DEFOG", "HURRICANE", "BOOMBURST" },
  },
  TANGELA = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "TANGELA",
    eggMoves = { "MEGA_DRAIN", "LEECH_SEED", "CONFUSION", "REFLECT", "AMNESIA", "FLAIL", "GIGA_DRAIN", "NATURE_POWER", "ENDEAVOR", "WAKE_UP_SLAP", "NATURAL_GIFT", "POWER_SWAP", "LEAF_STORM", "RAGE_POWDER" },
  },
  TAUROS = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TAUROS",
    eggMoves = { "CURSE", "ENDEAVOR" },
  },
  TEDDIURSA = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TEDDIURSA",
    eggMoves = { "TAKE_DOWN", "DOUBLE_EDGE", "COUNTER", "SEISMIC_TOSS", "FOCUS_ENERGY", "BELLY_DRUM", "FURY_CUTTER", "SLEEP_TALK", "METAL_CLAW", "CROSS_CHOP", "CRUNCH", "YAWN", "FAKE_TEARS", "CLOSE_COMBAT", "NIGHT_SLASH", "CHIP_AWAY", "PLAY_ROUGH" },
  },
  TENTACOOL = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "TENTACOOL",
    eggMoves = { "AURORA_BEAM", "CONFUSE_RAY", "HAZE", "BUBBLE", "SAFEGUARD", "RAPID_SPIN", "MIRROR_COAT", "KNOCK_OFF", "TICKLE", "MUDDY_WATER", "ACUPRESSURE", "AQUA_RING" },
  },
  TENTACRUEL = {
    eggGroups = { "WATER_3" },
    hatchCounter = 20,
    babySpecies = "TENTACOOL",
    evolvesFrom = "TENTACOOL",
    eggMoves = { "AURORA_BEAM", "CONFUSE_RAY", "HAZE", "RAPID_SPIN", "MIRROR_COAT", "KNOCK_OFF", "TICKLE", "ACUPRESSURE", "AQUA_RING" },
  },
  TOGEPI = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 10,
    babySpecies = "TOGEPI",
    eggMoves = { "PECK", "MIRROR_MOVE", "SUBSTITUTE", "FORESIGHT", "PRESENT", "MORNING_SUN", "PSYCH_UP", "FUTURE_SIGHT", "SECRET_POWER", "EXTRASENSORY", "AERIAL_ACE", "PSYCHO_SHIFT", "LUCKY_CHANT", "NASTY_PLOT", "STORED_POWER" },
  },
  TOGETIC = {
    eggGroups = { "FLYING", "FAIRY" },
    hatchCounter = 10,
    babySpecies = "TOGEPI",
    evolvesFrom = "TOGEPI",
    eggMoves = {  },
  },
  TORCHIC = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TORCHIC",
    eggMoves = { "PECK", "LOW_KICK", "COUNTER", "AGILITY", "ROCK_SLIDE", "CURSE", "REVERSAL", "ENDURE", "SWAGGER", "BATON_PASS", "SMELLING_SALTS", "FEATHER_DANCE", "CRUSH_CLAW", "FEINT", "LAST_RESORT", "NIGHT_SLASH", "FLAME_BURST" },
  },
  TORKOAL = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TORKOAL",
    eggMoves = { "EARTHQUAKE", "FISSURE", "SKULL_BASH", "FLAIL", "ENDURE", "SLEEP_TALK", "ANCIENT_POWER", "SUPERPOWER", "YAWN", "ERUPTION", "FLAME_BURST", "CLEAR_SMOG" },
  },
  TOTODILE = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "TOTODILE",
    eggMoves = { "ICE_PUNCH", "RAZOR_WIND", "THRASH", "HYDRO_PUMP", "COUNTER", "ROCK_SLIDE", "METAL_CLAW", "CRUNCH", "ANCIENT_POWER", "FLATTER", "MUD_SPORT", "FAKE_TEARS", "BLOCK", "DRAGON_CLAW", "WATER_SPORT", "DRAGON_DANCE", "WATER_PULSE", "AQUA_JET" },
  },
  TRAPINCH = {
    eggGroups = { "BUG", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "TRAPINCH",
    eggMoves = { "GUST", "QUICK_ATTACK", "FOCUS_ENERGY", "FLAIL", "ENDURE", "FURY_CUTTER", "SIGNAL_BEAM", "MUD_SHOT", "FEINT", "EARTH_POWER", "BUG_BITE", "FIRST_IMPRESSION" },
  },
  TREECKO = {
    eggGroups = { "MONSTER", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "TREECKO",
    eggMoves = { "RAZOR_WIND", "DOUBLE_KICK", "ABSORB", "LEECH_SEED", "SLASH", "DRAGON_BREATH", "SYNTHESIS", "CRUNCH", "ENDEAVOR", "MUD_SPORT", "CRUSH_CLAW", "GRASS_WHISTLE", "BULLET_SEED", "MAGICAL_LEAF", "NATURAL_GIFT", "WORRY_SEED", "NIGHT_SLASH", "LEAF_STORM", "GRASSY_TERRAIN" },
  },
  TROPIUS = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 25,
    babySpecies = "TROPIUS",
    eggMoves = { "RAZOR_WIND", "SLAM", "HEADBUTT", "LEECH_SEED", "CURSE", "SYNTHESIS", "NATURE_POWER", "BULLET_SEED", "LEAF_BLADE", "DRAGON_DANCE", "NATURAL_GIFT", "LEAF_STORM", "DRAGON_HAMMER" },
  },
  TYPHLOSION = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "CYNDAQUIL",
    evolvesFrom = "QUILAVA",
    eggMoves = { "DOUBLE_KICK", "CURSE", "REVERSAL", "EXTRASENSORY", "HOWL", "COVET" },
  },
  TYRANITAR = {
    eggGroups = { "MONSTER" },
    hatchCounter = 40,
    babySpecies = "LARVITAR",
    evolvesFrom = "PUPITAR",
    eggMoves = {  },
  },
  TYROGUE = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 25,
    babySpecies = "TYROGUE",
    eggMoves = { "COUNTER", "HI_JUMP_KICK", "MIND_READER", "MACH_PUNCH", "ENDURE", "PURSUIT", "RAPID_SPIN", "HELPING_HAND", "FEINT", "VACUUM_WAVE", "BULLET_PUNCH", "ALLY_SWITCH" },
  },
  UMBREON = {
    eggGroups = { "FIELD" },
    hatchCounter = 35,
    babySpecies = "EEVEE",
    evolvesFrom = "EEVEE",
    eggMoves = {  },
  },
  UNOWN = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 40,
    babySpecies = "UNOWN",
    eggMoves = {  },
  },
  URSARING = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "TEDDIURSA",
    evolvesFrom = "TEDDIURSA",
    eggMoves = {  },
  },
  VAPOREON = {
    eggGroups = { "FIELD" },
    hatchCounter = 35,
    babySpecies = "EEVEE",
    evolvesFrom = "EEVEE",
    eggMoves = {  },
  },
  VENOMOTH = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "VENONAT",
    evolvesFrom = "VENONAT",
    eggMoves = {  },
  },
  VENONAT = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "VENONAT",
    eggMoves = { "AGILITY", "SCREECH", "GIGA_DRAIN", "BATON_PASS", "MORNING_SUN", "SKILL_SWAP", "SECRET_POWER", "SIGNAL_BEAM", "TOXIC_SPIKES", "BUG_BITE", "VENOSHOCK", "RAGE_POWDER" },
  },
  VENUSAUR = {
    eggGroups = { "MONSTER", "GRASS" },
    hatchCounter = 20,
    babySpecies = "BULBASAUR",
    evolvesFrom = "IVYSAUR",
    eggMoves = { "PETAL_DANCE", "TOXIC", "CURSE", "INGRAIN" },
  },
  VIBRAVA = {
    eggGroups = { "BUG", "DRAGON" },
    hatchCounter = 20,
    babySpecies = "TRAPINCH",
    evolvesFrom = "TRAPINCH",
    eggMoves = { "GUST", "SUPERSONIC", "FISSURE", "QUICK_ATTACK", "FLAIL", "FURY_CUTTER", "CRUNCH", "SUPERPOWER", "ASTONISH", "FEINT", "BUG_BITE", "BULLDOZE", "FIRST_IMPRESSION" },
  },
  VICTREEBEL = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "BELLSPROUT",
    evolvesFrom = "WEEPINBELL",
    eggMoves = { "SYNTHESIS", "STOCKPILE", "SPIT_UP", "SWALLOW", "INGRAIN", "TICKLE", "GASTRO_ACID", "WORRY_SEED", "SUCKER_PUNCH", "POWER_WHIP", "CLEAR_SMOG", "STRENGTH_SAP" },
  },
  VIGOROTH = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "SLAKOTH",
    evolvesFrom = "SLAKOTH",
    eggMoves = {  },
  },
  VILEPLUME = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "ODDISH",
    evolvesFrom = "GLOOM",
    eggMoves = { "LEECH_SEED", "RAZOR_LEAF", "FLAIL", "SYNTHESIS", "INGRAIN", "TEETER_DANCE", "TICKLE", "AFTER_YOU", "STRENGTH_SAP" },
  },
  VOLBEAT = {
    eggGroups = { "BUG", "HUMAN_LIKE" },
    hatchCounter = 15,
    babySpecies = "VOLBEAT",
    eggMoves = { "COUNTER", "SEISMIC_TOSS", "DIZZY_PUNCH", "SWAGGER", "BATON_PASS", "ENCORE", "TRICK", "SILVER_WIND", "ROOST", "BUG_BUZZ", "LUNGE" },
  },
  VOLTORB = {
    eggGroups = { "MINERAL" },
    hatchCounter = 20,
    babySpecies = "VOLTORB",
    eggMoves = { "RECYCLE", "METAL_SOUND" },
  },
  VULPIX = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "VULPIX",
    eggMoves = { "ROAR", "DISABLE", "HYPNOSIS", "FLAIL", "SPITE", "FEINT_ATTACK", "PSYCH_UP", "HEAT_WAVE", "MEMENTO", "SECRET_POWER", "EXTRASENSORY", "HOWL", "HEALING_WISH", "POWER_SWAP", "FLARE_BLITZ", "ENERGY_BALL", "CAPTIVATE", "FLAME_CHARGE", "HEX", "TAIL_SLAP", "BABY_DOLL_EYES" },
  },
  WAILMER = {
    eggGroups = { "FIELD", "WATER_2" },
    hatchCounter = 40,
    babySpecies = "WAILMER",
    eggMoves = { "BODY_SLAM", "THRASH", "DOUBLE_EDGE", "FISSURE", "DEFENSE_CURL", "SNORE", "CURSE", "ROLLOUT", "SWAGGER", "SLEEP_TALK", "TICKLE", "AQUA_RING", "ZEN_HEADBUTT", "SOAK", "CLEAR_SMOG" },
  },
  WAILORD = {
    eggGroups = { "FIELD", "WATER_2" },
    hatchCounter = 40,
    babySpecies = "WAILMER",
    evolvesFrom = "WAILMER",
    eggMoves = {  },
  },
  WALREIN = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "SPHEAL",
    evolvesFrom = "SEALEO",
    eggMoves = {  },
  },
  WARTORTLE = {
    eggGroups = { "MONSTER", "WATER_1" },
    hatchCounter = 20,
    babySpecies = "SQUIRTLE",
    evolvesFrom = "SQUIRTLE",
    eggMoves = { "MIST", "FLAIL", "MIRROR_COAT", "FAKE_OUT", "YAWN", "WATER_SPOUT", "AQUA_RING", "AQUA_JET", "LIFE_DEW" },
  },
  WEEDLE = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WEEDLE",
    eggMoves = {  },
  },
  WEEPINBELL = {
    eggGroups = { "GRASS" },
    hatchCounter = 20,
    babySpecies = "BELLSPROUT",
    evolvesFrom = "BELLSPROUT",
    eggMoves = { "SYNTHESIS", "INGRAIN", "TICKLE", "WORRY_SEED", "SUCKER_PUNCH", "CLEAR_SMOG", "STRENGTH_SAP" },
  },
  WEEZING = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "KOFFING",
    evolvesFrom = "KOFFING",
    eggMoves = {  },
  },
  WHISCASH = {
    eggGroups = { "WATER_2" },
    hatchCounter = 20,
    babySpecies = "BARBOACH",
    evolvesFrom = "BARBOACH",
    eggMoves = {  },
  },
  WHISMUR = {
    eggGroups = { "MONSTER", "FIELD" },
    hatchCounter = 20,
    babySpecies = "WHISMUR",
    eggMoves = { "WHIRLWIND", "TAKE_DOWN", "SMOKESCREEN", "SNORE", "SWAGGER", "SMELLING_SALTS", "ENDEAVOR", "FAKE_TEARS", "EXTRASENSORY", "HAMMER_ARM", "CIRCLE_THROW", "DISARMING_VOICE" },
  },
  WIGGLYTUFF = {
    eggGroups = { "FAIRY" },
    hatchCounter = 10,
    babySpecies = "IGGLYBUFF",
    evolvesFrom = "JIGGLYPUFF",
    eggMoves = {  },
  },
  WINGULL = {
    eggGroups = { "WATER_1", "FLYING" },
    hatchCounter = 20,
    babySpecies = "WINGULL",
    eggMoves = { "GUST", "MIST", "AGILITY", "TWISTER", "KNOCK_OFF", "AIR_CUTTER", "AERIAL_ACE", "WATER_SPORT", "ROOST", "BRINE", "AQUA_RING", "WIDE_GUARD", "SOAK" },
  },
  WOBBUFFET = {
    eggGroups = { "AMORPHOUS" },
    hatchCounter = 20,
    babySpecies = "WYNAUT",
    evolvesFrom = "WYNAUT",
    eggMoves = {  },
  },
  WOOPER = {
    eggGroups = { "WATER_1", "FIELD" },
    hatchCounter = 20,
    babySpecies = "WOOPER",
    eggMoves = { "DOUBLE_KICK", "BODY_SLAM", "COUNTER", "RECOVER", "CURSE", "SLEEP_TALK", "SAFEGUARD", "ENCORE", "ANCIENT_POWER", "STOCKPILE", "SPIT_UP", "SWALLOW", "MUD_SPORT", "GUARD_SWAP", "ACID_SPRAY", "AFTER_YOU", "EERIE_IMPULSE", "POWER_UP_PUNCH" },
  },
  WURMPLE = {
    eggGroups = { "BUG" },
    hatchCounter = 15,
    babySpecies = "WURMPLE",
    eggMoves = {  },
  },
  WYNAUT = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 20,
    babySpecies = "WYNAUT",
    eggMoves = {  },
  },
  XATU = {
    eggGroups = { "FLYING" },
    hatchCounter = 20,
    babySpecies = "NATU",
    evolvesFrom = "NATU",
    eggMoves = {  },
  },
  YANMA = {
    eggGroups = { "BUG" },
    hatchCounter = 20,
    babySpecies = "YANMA",
    eggMoves = { "WHIRLWIND", "DOUBLE_EDGE", "LEECH_LIFE", "REVERSAL", "FEINT_ATTACK", "PURSUIT", "SECRET_POWER", "SILVER_WIND", "SIGNAL_BEAM", "FEINT" },
  },
  ZANGOOSE = {
    eggGroups = { "FIELD" },
    hatchCounter = 20,
    babySpecies = "ZANGOOSE",
    eggMoves = { "RAZOR_WIND", "DOUBLE_KICK", "ROAR", "DISABLE", "COUNTER", "FURY_SWIPES", "CURSE", "FLAIL", "BELLY_DRUM", "IRON_TAIL", "METAL_CLAW", "FEINT", "NIGHT_SLASH", "DOUBLE_HIT", "QUICK_GUARD", "FINAL_GAMBIT" },
  },
  ZAPDOS = {
    eggGroups = { "UNDISCOVERED" },
    hatchCounter = 80,
    babySpecies = "ZAPDOS",
    eggMoves = {  },
  },
  ZIGZAGOON = {
    eggGroups = { "FIELD" },
    hatchCounter = 15,
    babySpecies = "ZIGZAGOON",
    eggMoves = { "SUBSTITUTE", "MUD_SLAP", "CHARM", "SLEEP_TALK", "PURSUIT", "EXTREME_SPEED", "HELPING_HAND", "TRICK", "TICKLE", "ROCK_CLIMB", "SIMPLE_BEAM" },
  },
  ZUBAT = {
    eggGroups = { "FLYING" },
    hatchCounter = 15,
    babySpecies = "ZUBAT",
    eggMoves = { "GUST", "WING_ATTACK", "WHIRLWIND", "HYPNOSIS", "QUICK_ATTACK", "CURSE", "FEINT_ATTACK", "GIGA_DRAIN", "STEEL_WING", "PURSUIT", "BRAVE_BIRD", "NASTY_PLOT", "ZEN_HEADBUTT", "DEFOG", "VENOM_DRENCH" },
  },
}

return P
