return {
  backupWarp = {
    map = "GOLDENROD_CITY",
    warp = 13,
  },
  bagOrder = {
    [1] = "FULL_HEAL",
    [2] = "RARE_CANDY",
    [3] = "ULTRA_BALL",
    [4] = "MASTER_BALL",
    [5] = "HEAVY_BALL",
    [6] = "FAST_BALL",
    [7] = "BICYCLE",
    [8] = "REPEL",
    [9] = "MAX_POTION",
    [10] = "FULL_RESTORE",
    [11] = "REVIVE",
    [12] = "MAX_REVIVE",
    [13] = "HM_STRENGTH",
    [14] = "HM_FLASH",
    [15] = "HM_WHIRLPOOL",
    [16] = "HM_WATERFALL",
    [17] = "HM_SURF",
    [18] = "HM_FLY",
    [19] = "HM_CUT",
    [20] = "MAX_REPEL",
    [21] = "S_S_TICKET",
    [22] = "PASS",
    [23] = "GOOD_ROD",
    [24] = "SUPER_ROD",
    [25] = "OLD_ROD",
    [26] = "COIN_CASE",
  },
  blackoutMap = "GOLDENROD_CITY",
  boxNames = {},
  boxes = {
    [1] = {},
    [2] = {},
    [3] = {},
    [4] = {},
    [5] = {},
    [6] = {},
    [7] = {},
    [8] = {},
    [9] = {},
    [10] = {},
    [11] = {},
    [12] = {},
    [13] = {},
    [14] = {},
  },
  bugContest = {},
  createdAt = 1786894933,
  currentBox = 1,
  dailyFlags = {},
  dailyReset = {
    day = 108,
    remaining = 1,
  },
  dayCare = {
    compatible = false,
    hasEgg = false,
    lady = {},
    man = {},
    stepsToEgg = 0,
  },
  decorations = {
    bed = 2,
    poster = 16,
  },
  engineFlags = {
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [16] = true,
    [17] = true,
    [18] = true,
    [19] = true,
    [20] = true,
    [21] = true,
    [22] = true,
    [23] = true,
    [34] = true,
    [35] = true,
    [36] = true,
    [37] = true,
    [38] = true,
    [39] = true,
    [40] = true,
    [41] = true,
    [53] = true,
    [61] = true,
    [64] = true,
    [65] = true,
    [69] = true,
  },
  events = {
    [3] = 36,
    [4] = 32,
    [6] = 64,
    [25] = 32,
    [31] = 8,
    [84] = 16,
    [85] = 128,
    [89] = 16,
    [96] = 144,
    [131] = 40,
    [144] = 2,
    [168] = 64,
    [181] = 64,
    [200] = 4,
    [215] = 192,
    [216] = 207,
    [217] = 104,
    [218] = 57,
    [219] = 225,
    [220] = 208,
    [221] = 255,
    [222] = 31,
    [223] = 162,
    [224] = 29,
    [225] = 224,
    [226] = 239,
    [227] = 255,
    [228] = 255,
    [229] = 179,
    [230] = 106,
    [231] = 189,
    [232] = 30,
    [233] = 38,
    [235] = 128,
    [236] = 96,
    [237] = 240,
    [238] = 204,
    [239] = 8,
    [262] = 0,
    [263] = 0,
    [275] = 0,
    [374] = 0,
    [375] = 62,
  },
  firstUnownSeen = 0,
  flags = {
    [1] = "EVENT_BEAT_ELITE_FOUR",
    [2] = "EVENT_BEAT_CHAMPION_LANCE",
    [3] = "EVENT_S_S_TICKET",
    MOD_DEX_RECOVERED = true,
  },
  format = 7,
  generation = 2,
  hallOfFame = {
    count = 0,
    teams = {},
  },
  happinessStepCount = 0,
  inventory = {
    BICYCLE = 1,
    COIN_CASE = 1,
    FAST_BALL = 99,
    FULL_HEAL = 99,
    FULL_RESTORE = 99,
    GOOD_ROD = 1,
    HEAVY_BALL = 99,
    HM_CUT = 1,
    HM_FLASH = 1,
    HM_FLY = 1,
    HM_STRENGTH = 1,
    HM_SURF = 1,
    HM_WATERFALL = 1,
    HM_WHIRLPOOL = 1,
    MASTER_BALL = 99,
    MAX_POTION = 99,
    MAX_REPEL = 99,
    MAX_REVIVE = 99,
    OLD_ROD = 1,
    PASS = 1,
    RARE_CANDY = 99,
    REPEL = 99,
    REVIVE = 99,
    SUPER_ROD = 1,
    S_S_TICKET = 1,
    ULTRA_BALL = 99,
  },
  lastDexMode = "NEW",
  mail = {
    box = {},
    party = {},
  },
  mapScenes = {
    ELMS_LAB = 2,
    NEW_BARK_TOWN = 1,
    PLAYERS_HOUSE_1F = 1,
  },
  meta = {
    format = 4,
    krNote = "KR campaign test: pre-Silver (Safari cleared + 8 badges)",
    mods = {},
  },
  modData = {
    ["Kanto-Reforged"] = {
      ["g2:farmSteps"] = 1208,
      ["g2:plots"] = {},
      ["g2:pokedex_flags"] = {
        caught = {
          CASTFORM = true,
          CHIKORITA = true,
          DRAGONITE = true,
          ESPEON = true,
          KINGDRA = true,
          SCIZOR = true,
          TYPHLOSION = true,
          TYRANITAR = true,
        },
        owned = {
          CASTFORM = true,
          CHIKORITA = true,
          DRAGONITE = true,
          ESPEON = true,
          KINGDRA = true,
          SCIZOR = true,
          TYPHLOSION = true,
          TYRANITAR = true,
        },
        seen = {
          CASTFORM = true,
          CHIKORITA = true,
          CLEFABLE = true,
          DIGLETT = true,
          DRAGONITE = true,
          ESPEON = true,
          GARDEVOIR = true,
          GOLBAT = true,
          GROWLITHE = true,
          KANGASKHAN = true,
          KINGDRA = true,
          MAGNETON = true,
          MANKEY = true,
          MARILL = true,
          METANG = true,
          MIGHTYENA = true,
          MUK = true,
          PORYGON2 = true,
          PSYDUCK = true,
          RATICATE = true,
          SANDSHREW = true,
          SCIZOR = true,
          TYPHLOSION = true,
          TYRANITAR = true,
          VULPIX = true,
          WEEZING = true,
          WIGGLYTUFF = true,
        },
      },
      pokedex_flags = {
        caught = {
          CASTFORM = true,
          CHIKORITA = true,
          DRAGONITE = true,
          ESPEON = true,
          KINGDRA = true,
          SCIZOR = true,
          TYPHLOSION = true,
          TYRANITAR = true,
        },
        owned = {
          CASTFORM = true,
          CHIKORITA = true,
          DRAGONITE = true,
          ESPEON = true,
          KINGDRA = true,
          SCIZOR = true,
          TYPHLOSION = true,
          TYRANITAR = true,
        },
        seen = {
          CASTFORM = true,
          CHIKORITA = true,
          CLEFABLE = true,
          DIGLETT = true,
          DRAGONITE = true,
          ESPEON = true,
          GARDEVOIR = true,
          GOLBAT = true,
          GROWLITHE = true,
          KANGASKHAN = true,
          KINGDRA = true,
          MAGNETON = true,
          MANKEY = true,
          MARILL = true,
          METANG = true,
          MIGHTYENA = true,
          MUK = true,
          PORYGON2 = true,
          PSYDUCK = true,
          RATICATE = true,
          SANDSHREW = true,
          SCIZOR = true,
          TYPHLOSION = true,
          TYRANITAR = true,
          VULPIX = true,
          WEEZING = true,
          WIGGLYTUFF = true,
        },
      },
    },
  },
  mom = {
    active = false,
    name = "MOM",
    savedMoney = 0,
    savingMoney = false,
    triggerBalance = 2300,
    whichItem = 0,
  },
  options = {
    activeProfile = "PROFILE 1",
    battleScene = true,
    battleStyle = "SHIFT",
    color = "gbc",
    fpsCap = 60,
    frame = 1,
    gbcfx = 0,
    haptics = "light",
    menuAccount = true,
    modOptions = {
      ["Kanto-Reforged"] = {
        battle_exp_bar = true,
        battle_ruleset = "modern_clean",
        battle_ruleset_seeded = true,
        dexnav_mode = "dexnav",
        full_spawn_random = false,
        ["g1:full_spawn_random"] = false,
        ["g1:legends_in_mix"] = false,
        ["g1:pure_spawn_random"] = false,
        ["g1:species_scope"] = "national",
        ["g2:full_spawn_random"] = false,
        ["g2:legends_in_mix"] = false,
        ["g2:pure_spawn_random"] = false,
        ["g2:species_scope"] = "national",
        legends_in_mix = false,
        location_signposts = true,
        modern_xp_share = true,
        pure_spawn_random = false,
        species_scope = "national",
        split_special = true,
        switch_hit_ai = "gen3",
      },
      location_signposts = {
        night_mode = "auto",
        signpost_style = "firered",
      },
    },
    modProfiles = {
      [1] = {
        enabled = {
          ["Kanto-Reforged"] = false,
          example_mew_starter = false,
          gen1_modern_ui = false,
          pokegear_cards = false,
        },
        enabledByVersion = {
          blue = {
            gen1_modern_ui = true,
            nuzlocke = false,
          },
          gold = {
            gen1_modern_ui = true,
            nuzlocke = false,
          },
          red = {
            nuzlocke = false,
          },
          yellow = {
            gen1_modern_ui = true,
            nuzlocke = false,
          },
        },
        name = "test 1",
        options = {
          ["Kanto-Reforged"] = {
            dexnav_mode = "dexnav",
            full_spawn_random = false,
            ["g1:full_spawn_random"] = false,
            ["g1:legends_in_mix"] = false,
            ["g1:pure_spawn_random"] = false,
            ["g1:species_scope"] = "national",
            ["g2:full_spawn_random"] = true,
            ["g2:legends_in_mix"] = true,
            ["g2:pure_spawn_random"] = true,
            ["g2:species_scope"] = "national",
            legends_in_mix = false,
            location_signposts = true,
            pure_spawn_random = false,
            species_scope = "national",
            split_special = true,
          },
        },
        slots = {
          gold = "slot1",
          red = "slot7",
        },
      },
      [2] = {
        enabled = {
          ["Kanto-Reforged"] = false,
          example_mew_starter = false,
          gen1_modern_ui = false,
          pokegear_cards = false,
        },
        enabledByVersion = {
          blue = {
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
            pokegear_cards = false,
          },
          gold = {
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
          },
          red = {
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
            pokegear_cards = false,
          },
          yellow = {
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
            pokegear_cards = false,
          },
        },
        name = "test 1 (Copy)",
        options = {
          ["Kanto-Reforged"] = {
            dexnav_mode = "dexnav",
            full_spawn_random = false,
            ["g2:full_spawn_random"] = true,
            ["g2:legends_in_mix"] = true,
            ["g2:pure_spawn_random"] = true,
            ["g2:species_scope"] = "national",
            legends_in_mix = false,
            pure_spawn_random = false,
            species_scope = "national",
            split_special = true,
          },
        },
        slots = {
          gold = "slot1",
          red = "slot7",
        },
      },
      [3] = {
        enabled = {
          DRAMALESS_SHAPE = false,
          ["Kanto-Reforged"] = false,
          example_mew_starter = false,
          ["game-corner-hub"] = false,
          gen1_modern_ui = false,
          location_signposts = false,
          pokegear_cards = false,
          right_stick_move = false,
        },
        enabledByVersion = {
          blue = {
            DRAMALESS_SHAPE = false,
            ["Kanto-Reforged"] = false,
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
            pokegear_cards = false,
            ["standalone-bag-pockets"] = false,
          },
          gold = {
            DRAMALESS_SHAPE = false,
            ["Kanto-Reforged"] = true,
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
            pokegear_cards = true,
            ["standalone-bag-pockets"] = false,
          },
          red = {
            DRAMALESS_SHAPE = false,
            ["Kanto-Reforged"] = true,
            example_mew_starter = false,
            location_signposts = true,
            nuzlocke = false,
            pokegear_cards = false,
            ["standalone-bag-pockets"] = false,
          },
          silver = {
            DRAMALESS_SHAPE = false,
            ["Kanto-Reforged"] = false,
            example_mew_starter = false,
            pokegear_cards = false,
            ["standalone-bag-pockets"] = false,
          },
          yellow = {
            DRAMALESS_SHAPE = false,
            ["Kanto-Reforged"] = false,
            example_mew_starter = false,
            gen1_modern_ui = false,
            nuzlocke = false,
            pokegear_cards = false,
            ["standalone-bag-pockets"] = false,
          },
        },
        name = "PROFILE 1",
        options = {
          ["Kanto-Reforged"] = {
            battle_exp_bar = true,
            battle_ruleset = "modern_clean",
            battle_ruleset_seeded = true,
            dexnav_mode = "dexnav",
            full_spawn_random = false,
            ["g1:full_spawn_random"] = false,
            ["g1:legends_in_mix"] = false,
            ["g1:pure_spawn_random"] = false,
            ["g1:species_scope"] = "national",
            ["g2:full_spawn_random"] = false,
            ["g2:legends_in_mix"] = false,
            ["g2:pure_spawn_random"] = false,
            ["g2:species_scope"] = "national",
            legends_in_mix = false,
            location_signposts = true,
            modern_xp_share = true,
            pure_spawn_random = false,
            species_scope = "national",
            split_special = true,
            switch_hit_ai = "gen3",
          },
          location_signposts = {
            night_mode = "auto",
            signpost_style = "firered",
          },
        },
        slots = {
          gold = "slot3",
          red = "slot8",
          yellow = "slot2",
        },
      },
    },
    modProfilesSeeded = true,
    mods = {
      gen1_modern_ui = false,
      nuzlocke = false,
    },
    modsByVersion = {
      blue = {
        DRAMALESS_SHAPE = false,
        ["Kanto-Reforged"] = false,
        example_mew_starter = false,
        gen1_modern_ui = false,
        nuzlocke = false,
        pokegear_cards = false,
        ["standalone-bag-pockets"] = false,
      },
      gold = {
        DRAMALESS_SHAPE = false,
        ["Kanto-Reforged"] = true,
        example_mew_starter = false,
        gen1_modern_ui = false,
        nuzlocke = false,
        pokegear_cards = true,
        ["standalone-bag-pockets"] = false,
      },
      red = {
        DRAMALESS_SHAPE = false,
        ["Kanto-Reforged"] = true,
        example_mew_starter = false,
        location_signposts = true,
        nuzlocke = false,
        pokegear_cards = false,
        ["standalone-bag-pockets"] = false,
      },
      silver = {
        DRAMALESS_SHAPE = false,
        ["Kanto-Reforged"] = false,
        example_mew_starter = false,
        pokegear_cards = false,
        ["standalone-bag-pockets"] = false,
      },
      yellow = {
        DRAMALESS_SHAPE = false,
        ["Kanto-Reforged"] = false,
        example_mew_starter = false,
        gen1_modern_ui = false,
        nuzlocke = false,
        pokegear_cards = false,
        ["standalone-bag-pockets"] = false,
      },
    },
    modsGen2 = {},
    musicFilter = 2,
    musicVol = 3,
    print = "NORMAL",
    screenPos = "center",
    sfxVol = 7,
    sound = "MONO",
    speed = 3,
    textSpeed = "FAST",
    tilt = 0,
    touchControls = {
      enabled = true,
    },
    videoMode = "windowed",
    voidFill = "fade",
    zoom = -1,
  },
  party = {
    [1] = {
      caughtLevel = 62,
      dvs = {
        attack = 15,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 15,
      },
      experience = 8338,
      gender = "male",
      happiness = 255,
      hp = 76,
      item = "SILK_SCARF",
      level = 20,
      maxHp = 76,
      moves = {
        [1] = {
          id = "WEATHER_BALL",
          maxPp = 10,
          pp = 10,
        },
        [2] = {
          id = "SUNNY_DAY",
          maxPp = 5,
          pp = 5,
        },
        [3] = {
          id = "RAIN_DANCE",
          maxPp = 5,
          pp = 5,
        },
        [4] = {
          id = "HAIL",
          maxPp = 10,
          pp = 10,
        },
      },
      name = "CASTFORM",
      ot = "TAYLOR",
      otId = 7607,
      otName = "TAYLOR",
      pokerus = 0,
      shiny = false,
      species = "CASTFORM",
      statExp = {
        attack = 65535,
        defense = 65535,
        hp = 65535,
        special = 65535,
        speed = 65535,
      },
      stats = {
        attack = 51,
        defense = 51,
        hp = 76,
        specialAttack = 51,
        specialDefense = 51,
        speed = 51,
      },
      types = {
        [1] = "NORMAL",
      },
    },
    [2] = {
      caughtLevel = 62,
      dvs = {
        attack = 15,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 15,
      },
      experience = 279143,
      gender = "male",
      happiness = 255,
      hp = 236,
      item = "CHARCOAL",
      level = 65,
      maxHp = 236,
      moves = {
        [1] = {
          id = "FLAMETHROWER",
          maxPp = 30,
          pp = 30,
        },
        [2] = {
          id = "THUNDERPUNCH",
          maxPp = 30,
          pp = 30,
        },
        [3] = {
          id = "EARTHQUAKE",
          maxPp = 30,
          pp = 30,
        },
        [4] = {
          id = "SWIFT",
          maxPp = 30,
          pp = 30,
        },
      },
      name = "TYPHLOSION",
      ot = "TAYLOR",
      otId = 7607,
      otName = "TAYLOR",
      pokerus = 0,
      shiny = false,
      species = "TYPHLOSION",
      statExp = {
        attack = 65535,
        defense = 65535,
        hp = 65535,
        special = 65535,
        speed = 65535,
      },
      stats = {
        attack = 174,
        defense = 166,
        hp = 236,
        specialAttack = 207,
        specialDefense = 175,
        speed = 195,
      },
      types = {
        [1] = "FIRE",
        [2] = "FIRE",
      },
    },
    [3] = {
      caughtLevel = 62,
      dvs = {
        attack = 15,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 15,
      },
      experience = 239084,
      gender = "male",
      happiness = 255,
      hp = 253,
      item = "BLACK_GLASSES",
      level = 62,
      maxHp = 253,
      moves = {
        [1] = {
          id = "ROCK_SLIDE",
          maxPp = 30,
          pp = 30,
        },
        [2] = {
          id = "CRUNCH",
          maxPp = 30,
          pp = 30,
        },
        [3] = {
          id = "EARTHQUAKE",
          maxPp = 30,
          pp = 30,
        },
        [4] = {
          id = "HYPER_BEAM",
          maxPp = 30,
          pp = 30,
        },
      },
      name = "TYRANITAR",
      ot = "TAYLOR",
      otId = 7607,
      otName = "TAYLOR",
      pokerus = 0,
      shiny = false,
      species = "TYRANITAR",
      statExp = {
        attack = 65535,
        defense = 65535,
        hp = 65535,
        special = 65535,
        speed = 65535,
      },
      stats = {
        attack = 228,
        defense = 199,
        hp = 253,
        specialAttack = 180,
        specialDefense = 186,
        speed = 138,
      },
      types = {
        [1] = "ROCK",
        [2] = "DARK",
      },
    },
    [4] = {
      caughtLevel = 62,
      dvs = {
        attack = 15,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 15,
      },
      experience = 242448,
      gender = "male",
      happiness = 255,
      hp = 222,
      item = "DRAGON_SCALE",
      level = 62,
      maxHp = 222,
      moves = {
        [1] = {
          id = "SURF",
          maxPp = 30,
          pp = 30,
        },
        [2] = {
          id = "DRAGON_BREATH",
          maxPp = 30,
          pp = 30,
        },
        [3] = {
          id = "ICE_BEAM",
          maxPp = 30,
          pp = 30,
        },
        [4] = {
          id = "WATERFALL",
          maxPp = 30,
          pp = 30,
        },
      },
      name = "KINGDRA",
      ot = "TAYLOR",
      otId = 7607,
      otName = "TAYLOR",
      pokerus = 0,
      shiny = false,
      species = "KINGDRA",
      statExp = {
        attack = 65535,
        defense = 65535,
        hp = 65535,
        special = 65535,
        speed = 65535,
      },
      stats = {
        attack = 180,
        defense = 180,
        hp = 222,
        specialAttack = 180,
        specialDefense = 180,
        speed = 168,
      },
      types = {
        [1] = "WATER",
        [2] = "DRAGON",
      },
    },
    [5] = {
      caughtLevel = 62,
      dvs = {
        attack = 15,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 15,
      },
      experience = 238328,
      gender = "male",
      happiness = 255,
      hp = 210,
      item = "TWISTEDSPOON",
      level = 62,
      maxHp = 210,
      moves = {
        [1] = {
          id = "PSYCHIC",
          maxPp = 30,
          pp = 30,
        },
        [2] = {
          id = "SHADOW_BALL",
          maxPp = 30,
          pp = 30,
        },
        [3] = {
          id = "MORNING_SUN",
          maxPp = 30,
          pp = 30,
        },
        [4] = {
          id = "REFLECT",
          maxPp = 30,
          pp = 30,
        },
      },
      name = "ESPEON",
      ot = "TAYLOR",
      otId = 7607,
      otName = "TAYLOR",
      pokerus = 0,
      shiny = false,
      species = "ESPEON",
      statExp = {
        attack = 65535,
        defense = 65535,
        hp = 65535,
        special = 65535,
        speed = 65535,
      },
      stats = {
        attack = 143,
        defense = 137,
        hp = 210,
        specialAttack = 223,
        specialDefense = 180,
        speed = 199,
      },
      types = {
        [1] = "PSYCHIC_TYPE",
        [2] = "PSYCHIC_TYPE",
      },
    },
    [6] = {
      caughtLevel = 65,
      dvs = {
        attack = 15,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 15,
      },
      experience = 274725,
      gender = "male",
      happiness = 255,
      hp = 253,
      item = "DRAGON_FANG",
      level = 65,
      maxHp = 253,
      moves = {
        [1] = {
          id = "OUTRAGE",
          maxPp = 30,
          pp = 30,
        },
        [2] = {
          id = "FLY",
          maxPp = 30,
          pp = 30,
        },
        [3] = {
          id = "THUNDERBOLT",
          maxPp = 30,
          pp = 30,
        },
        [4] = {
          id = "SURF",
          maxPp = 30,
          pp = 30,
        },
      },
      name = "DRAGONITE",
      ot = "TAYLOR",
      otId = 7607,
      otName = "TAYLOR",
      pokerus = 0,
      shiny = false,
      species = "DRAGONITE",
      statExp = {
        attack = 65535,
        defense = 65535,
        hp = 65535,
        special = 65535,
        speed = 65535,
      },
      stats = {
        attack = 239,
        defense = 188,
        hp = 253,
        specialAttack = 195,
        specialDefense = 195,
        speed = 169,
      },
      types = {
        [1] = "DRAGON",
        [2] = "FLYING",
      },
    },
  },
  pcItems = {},
  phone = {
    delayMins = 19,
    delayStart = {
      day = 95,
      hour = 22,
      minute = 46,
    },
    list = {
      [1] = 1,
      [2] = 4,
      [3] = 0,
      [4] = 0,
      [5] = 0,
      [6] = 0,
      [7] = 0,
      [8] = 0,
      [9] = 0,
      [10] = 0,
    },
    specialCall = 0,
    timeCycles = 0,
  },
  phoneContacts = {
    [1] = true,
    [4] = true,
  },
  playTime = {
    frames = 22,
    hours = 0,
    minutes = 13,
    seconds = 41,
  },
  player = {
    badges = {
      FOG = true,
      GLACIER = true,
      HIVE = true,
      MINERAL = true,
      PLAIN = true,
      RISING = true,
      STORM = true,
      ZEPHYR = true,
    },
    coins = 9999,
    gender = "male",
    id = 7607,
    kantoBadges = {
      BOULDER = true,
      CASCADE = true,
      EARTH = true,
      MARSH = true,
      RAINBOW = true,
      SOUL = true,
      THUNDER = true,
      VOLCANO = true,
    },
    money = 999999,
    name = "TAYLOR",
  },
  playerState = "normal",
  poisonStepCount = 1,
  pokedex = {
    caught = {
      CASTFORM = true,
      CHIKORITA = true,
      DRAGONITE = true,
      ESPEON = true,
      KINGDRA = true,
      SCIZOR = true,
      TYPHLOSION = true,
      TYRANITAR = true,
    },
    owned = {
      CASTFORM = true,
      CHIKORITA = true,
      DRAGONITE = true,
      ESPEON = true,
      KINGDRA = true,
      SCIZOR = true,
      TYPHLOSION = true,
      TYRANITAR = true,
    },
    seen = {
      CASTFORM = true,
      CHIKORITA = true,
      CLEFABLE = true,
      DIGLETT = true,
      DRAGONITE = true,
      ESPEON = true,
      GARDEVOIR = true,
      GOLBAT = true,
      GROWLITHE = true,
      KANGASKHAN = true,
      KINGDRA = true,
      MAGNETON = true,
      MANKEY = true,
      MARILL = true,
      METANG = true,
      MIGHTYENA = true,
      MUK = true,
      PORYGON2 = true,
      PSYDUCK = true,
      RATICATE = true,
      SANDSHREW = true,
      SCIZOR = true,
      TYPHLOSION = true,
      TYRANITAR = true,
      VULPIX = true,
      WEEZING = true,
      WIGGLYTUFF = true,
    },
  },
  pokerusStartDay = 108,
  position = {
    facing = "up",
    map = "MT_MOON_B2F_KR",
    x = 5,
    y = 5,
  },
  rival = {
    name = "???",
  },
  rtc = {
    day = 228,
    dayOfWeek = 0,
    dst = true,
    hour = 10,
    minute = 42,
    startDay = 0,
    startMinute = 1398,
  },
  savedAt = 1788115049,
  scriptMem = {},
  spawn = "SPAWN_HOME",
  stepCount = 129,
  tradeFlags = {},
  unownDex = {},
  variableSprites = {
    [4] = 82,
    [5] = 4,
    [6] = 53,
    [7] = 10,
    [8] = 10,
    [9] = 10,
    [10] = 10,
    [11] = 40,
    [12] = 40,
  },
  version = "gold",
}
